import SitDropdown from "../Dropdown/sit-dropdown";
import SitDropdownItem from "../Dropdown/sit-dropdown-item";
import SitIcon from "../Icon/sit-icon";
import SitElement from "../../base/sit-element";
/**
 * @slot default - The menu items. Pass in sit-dropdown-item as the menu items
 * @slot toggler - The content of the toggler to pass in html content.
 */
export declare class SitMainnavDropdown extends SitElement {
    static styles: import("lit").CSSResult[];
    /** @internal */
    static dependencies: {
        "sit-dropdown": typeof SitDropdown;
        "sit-dropdown-item": typeof SitDropdownItem;
        "sit-icon": typeof SitIcon;
    };
    private _breakpointReached;
    private expanded;
    /** @internal */
    navLink: HTMLElement;
    /** @internal */
    dropdownItems: HTMLElement;
    /** @internal */
    menuHeaderButton: HTMLElement;
    /** @internal */
    menuHeaderText: HTMLElement;
    /** @internal Forwards value to id attribute of toggle button of Dropdown. An unique id generated by default */
    private togglerId;
    /** When true,  applies active styles on the dropdown button */
    active: boolean;
    /** When true,  applies active styles on the dropdown button */
    disabled: boolean;
    /**
     * Accessible label for the dropdown's toggle button. Forwarded to the button's aria-label attribute.
     */
    ariaLabel: string;
    /** @internal */
    private togglerNodes;
    /** @internal */
    private defaultNodes;
    /** @internal */
    get defaultSlotItems(): SitDropdownItem[];
    updated(): void;
    private _handleSlotChange;
    private _handleDesktopSlotChange;
    private _handleKeyboardMenuItemsEvent;
    private _copyTextToMenu;
    private _hideDropdownMenuItems;
    private _resetDropdownMenu;
    private _handleKeyboardOpen;
    private _getNavbarBody;
    private _openMenu;
    private _handleHeaderKeyboardEvent;
    private _closeMenu;
    render(): import("lit-html").TemplateResult<1>;
}
export default SitMainnavDropdown;
