'use client';
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var lit = require('lit');

var css_248z = lit.css`.footer{background-color:var(--sit-bg-fixed-dark);height:auto}.footer-top{border-bottom:var(--sit-border-width-1) solid var(--sit-border-color-default);display:flex;flex-direction:column;padding:var(--sit-padding-2-xl) var(--sit-padding-none)}.footer-top.has-content{gap:var(--sit-gap-2-xl)}.footer-header{display:flex;flex-direction:column;gap:var(--sit-gap-sm)}slot[name=title]::slotted(*){color:var(--sit-color-fixed-light)!important;font-size:var(--sit-font-size-heading-md)!important;font-weight:var(--sit-font-weight-semibold);letter-spacing:var(--sit-letter-spacing-tight);line-height:var(--sit-line-height-md)!important;margin-bottom:var(--sit-margin-none)!important;margin-top:var(--sit-margin-none)}slot:not([name])::slotted(*),slot[name=description]::slotted(*){color:var(--sit-color-fixed-light);margin-bottom:var(--sit-margin-none)!important;margin-top:var(--sit-margin-none)}.footer-items{display:grid;gap:var(--sit-gap-md) var(--sit-gap-lg);grid-template-columns:repeat(auto-fit,minmax(240px,1fr))}.footer ul{margin:0;padding:0}.footer ul li{list-style-type:none}.footer-bottom{display:flex;flex-direction:column;gap:var(--sit-gap-md);padding:var(--sit-padding-2-xl) var(--sit-padding-none)}.footer-mandatory-links{display:flex;flex-direction:column;flex-wrap:wrap;gap:var(--sit-gap-xl);justify-content:space-between}.footer-mandatory-links ul{display:flex;flex-direction:column;flex-wrap:wrap;gap:var(--sit-gap-sm)}.footer-mandatory-links ul li a,.footer-mandatory-links ul li a:focus,.footer-mandatory-links ul li a:hover{color:var(--sit-color-fixed-light)}.footer-mandatory-links ul li a:focus-visible{outline:var(--sit-outline-focus);outline-offset:var(--sit-outline-offset-focus)}.footer-copyrights{color:var(--sit-color-fixed-light);font-size:var(--sit-font-size-label-sm);line-height:var(--sit-line-height-2-xs)}@media (min-width:768px){.footer-mandatory-links ul{flex-direction:row;gap:var(--sit-gap-sm) var(--sit-gap-xl)}}@media (min-width:1024px){.footer-top{padding:var(--sit-padding-3-xl) var(--sit-padding-none)}.footer-top.has-content{gap:var(--sit-gap-3-xl)}slot[name=title]::slotted(*){font-size:var(--sit-font-size-heading-md)!important;line-height:var(--sit-line-height-md)!important}.footer-mandatory-links ul{gap:var(--sit-gap-xl)}}@media (min-width:1280px){.footer-mandatory-links{flex-direction:row}}:host([tone=neutral]) .footer{background-color:var(--sit-bg-default)}:host([tone=neutral]) slot[name=title]::slotted(*){color:var(--sit-color-default)!important}:host([tone=neutral]) slot:not([name])::slotted(*),:host([tone=neutral]) slot[name=description]::slotted(*){color:var(--sit-color-default)}:host([tone=neutral]) .footer-copyrights{color:var(--sit-color-default)}`;

exports["default"] = css_248z;
//# sourceMappingURL=footer.cjs.js.map
