'use client';
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var tslib = require('tslib');
var lit = require('lit');
var context = require('@lit/context');
var decorators_js = require('lit/decorators.js');
var classMap_js = require('lit/directives/class-map.js');
var ifDefined_js = require('lit/directives/if-defined.js');
var dom = require('@floating-ui/dom');
var generateId = require('../../utils/generateId.cjs.js');
var dropdown = require('../Dropdown/dropdown.cjs.js');
var dropdownMenu = require('../Dropdown/dropdown-menu.cjs.js');
var mainnavDropdown = require('./mainnav-dropdown.cjs.js');
var sitDropdown = require('../Dropdown/sit-dropdown.cjs.js');
var sitDropdownItem = require('../Dropdown/sit-dropdown-item.cjs.js');
var sitIcon = require('../Icon/sit-icon.cjs.js');
var mainnavContext = require('./mainnav-context.cjs.js');
var sitElement = require('../../base/sit-element.cjs.js');

const TAB = "Tab";
const ENTER = "Enter";
const SPACE = " ";
/**
 * @slot default - The menu items. Pass in sit-dropdown-item as the menu items
 * @slot toggler - The content of the toggler to pass in html content.
 */
class SitMainnavDropdown extends sitElement["default"] {
    constructor() {
        super(...arguments);
        this._breakpointReached = true;
        /** @internal Forwards value to id attribute of toggle button of Dropdown. An unique id generated by default */
        this.togglerId = generateId["default"]("dropdown", "button");
        /** When true,  applies active styles on the dropdown button */
        this.active = false;
        /** When true,  applies active styles on the dropdown button */
        this.disabled = false;
    }
    /** @internal */
    get defaultSlotItems() {
        return [...(this.defaultNodes || [])].filter((node) => typeof node.tagName !== "undefined");
    }
    updated() {
        if (this._breakpointReached) {
            this._copyTextToMenu();
            this._resetDropdownMenu();
            this._hideDropdownMenuItems();
        }
    }
    _handleSlotChange(e) {
        const items = e.target.assignedElements({ flatten: true });
        items.forEach(item => {
            var _a;
            item.addEventListener("keydown", this._handleKeyboardMenuItemsEvent.bind(this));
            const dropdownItem = item.shadowRoot.querySelector(".dropdown-item");
            dropdownItem.classList.add("mainnav-dropdown-link");
            const link = ((_a = item.shadowRoot) === null || _a === void 0 ? void 0 : _a.querySelector("a")) || item.querySelector("a");
            link.tabIndex = -1;
            if (dropdownItem.classList.contains("disabled")) {
                link.setAttribute("href", "javascript:void(0)");
                link.setAttribute("tabindex", "-1");
            }
            else {
                link.addEventListener("click", (e) => {
                    const target = e.target;
                    const mainnav = target.closest("sit-mainnav");
                    mainnav.hide();
                });
            }
        });
    }
    _handleDesktopSlotChange(e) {
        const items = e.target.assignedElements({ flatten: true });
        items.forEach(item => {
            const dropdownItem = item.shadowRoot.querySelector(".dropdown-item");
            dropdownItem.classList.remove("mainnav-dropdown-link");
            const slottedItem = item.shadowRoot.querySelector(".dropdown-item slot").assignedElements({
                flatten: true
            });
            slottedItem.forEach(item => {
                if (dropdownItem.classList.contains("disabled")) {
                    item.setAttribute("href", "javascript:void(0)");
                    item.setAttribute("tabindex", "-1");
                }
            });
        });
    }
    _handleKeyboardMenuItemsEvent(e) {
        if (!this._breakpointReached) {
            return;
        }
        const slottedItems = this.defaultSlotItems.filter(item => !item.hasAttribute("disabled"));
        const items = [this.menuHeaderButton, ...slottedItems];
        const itemLength = items.length;
        if (itemLength === 0) {
            return;
        }
        const firstItem = items[0];
        const lastItem = items[itemLength - 1].shadowRoot.querySelector(".dropdown-item");
        let activeElement = document.activeElement;
        if (activeElement === this) {
            activeElement = this.shadowRoot.activeElement;
        }
        switch (e.key) {
            case "Tab": {
                if (e.shiftKey) {
                    if (activeElement === firstItem) {
                        e.preventDefault();
                        setTimeout(() => {
                            lastItem.focus();
                        }, 0);
                    }
                }
                else {
                    const activeShadowElement = activeElement.shadowRoot
                        ? activeElement.shadowRoot.querySelector(".dropdown-item")
                        : null;
                    if (activeShadowElement && activeShadowElement === lastItem) {
                        e.preventDefault();
                        firstItem.focus();
                    }
                }
                break;
            }
        }
    }
    _copyTextToMenu() {
        this.menuHeaderText.innerHTML = this.togglerNodes[0].innerHTML;
    }
    _hideDropdownMenuItems() {
        this.dropdownItems.style.display = "none";
        this.dropdownItems.setAttribute("aria-hidden", "true");
    }
    _resetDropdownMenu() {
        const navbarBody = this._getNavbarBody();
        if (!navbarBody)
            return Promise.resolve();
        return new Promise(resolve => {
            const onEnd = (event) => {
                if (event.propertyName === "transform") {
                    navbarBody.removeEventListener("transitionend", onEnd);
                    resolve();
                }
            };
            const hasTransition = getComputedStyle(navbarBody).transitionProperty.includes("transform");
            if (hasTransition) {
                navbarBody.addEventListener("transitionend", onEnd);
                navbarBody.style.removeProperty("transform");
            }
            else {
                navbarBody.style.removeProperty("transform");
                resolve();
            }
        });
    }
    _handleKeyboardOpen(event) {
        if (this.disabled) {
            return;
        }
        if (event.key === ENTER || event.key === SPACE) {
            event.preventDefault();
            this._openMenu();
        }
    }
    _getNavbarBody() {
        const mainNav = document.querySelector("sit-mainnav");
        if (!(mainNav === null || mainNav === void 0 ? void 0 : mainNav.shadowRoot)) {
            console.warn("sit-mainnav or its shadowRoot not found");
            return;
        }
        const navbarBody = mainNav.shadowRoot.querySelector(".navbar-body");
        if (!navbarBody) {
            console.warn(".navbar-body not found in sit-mainnav");
            return;
        }
        return navbarBody;
    }
    _openMenu() {
        const navbarBody = this._getNavbarBody();
        navbarBody.style.transform = "translateX(-100%)";
        this.dropdownItems.style.removeProperty("display");
        this.dropdownItems.setAttribute("aria-hidden", "false");
        setTimeout(() => {
            this.menuHeaderButton.focus();
        }, 50);
    }
    _handleHeaderKeyboardEvent(event) {
        switch (event.key) {
            case TAB: {
                this._handleKeyboardMenuItemsEvent(event);
                break;
            }
            case ENTER:
            case SPACE: {
                event.preventDefault();
                this._closeMenu();
                break;
            }
        }
    }
    async _closeMenu() {
        await this._resetDropdownMenu();
        this._hideDropdownMenuItems();
        this.navLink.focus();
    }
    render() {
        const mobileView = lit.html `
      <a
        class="${classMap_js.classMap({
            "nav-link": true,
            active: this.active,
            disabled: this.disabled
        })}"
        aria-disabled=${this.disabled ? "true" : "false"}
        aria-label=${ifDefined_js.ifDefined(this.ariaLabel)}
        tabindex=${this.disabled ? "-1" : "0"}
        role="button"
        @click=${this._openMenu}
        @keydown=${this._handleKeyboardOpen}
      >
        <slot name="toggler"></slot>
        <sit-icon name="chevron-right" size="md"></sit-icon>
      </a>
      <div class="dropdown-items">
        <a tabindex="0" role="button" @click=${this._closeMenu} @keydown=${this._handleHeaderKeyboardEvent}>
          <sit-icon name="chevron-left" size="md"></sit-icon>
          <span></span>
        </a>
        <slot @slotchange=${this._handleSlotChange}></slot>
      </div>
    `;
        const desktopView = lit.html `<sit-dropdown
      .floatingOpts=${{
            middleware: [dom.offset(0)]
        }}
      ?disabled=${this.disabled}
    >
      <a
        class="${classMap_js.classMap({
            "nav-link": true,
            active: this.active,
            disabled: this.disabled
        })}"
        aria-disabled=${this.disabled ? "true" : "false"}
        aria-label=${ifDefined_js.ifDefined(this.ariaLabel)}
        id=${this.togglerId}
        tabindex=${this.disabled ? "-1" : "0"}
        role="button"
        slot="toggler"
      >
        <slot name="toggler"></slot>
        <sit-icon name="chevron-down" size="md"></sit-icon>
      </a>
      <slot @slotchange=${this._handleDesktopSlotChange}></slot>
    </sit-dropdown>`;
        return this._breakpointReached ? mobileView : desktopView;
    }
}
SitMainnavDropdown.styles = [...sitElement["default"].styles, dropdown["default"], dropdownMenu["default"], mainnavDropdown["default"]];
/** @internal */
SitMainnavDropdown.dependencies = {
    "sit-dropdown": sitDropdown.SitDropdown,
    "sit-dropdown-item": sitDropdownItem.SitDropdownItem,
    "sit-icon": sitIcon.SitIcon
};
tslib.__decorate([
    context.consume({ context: mainnavContext.MainnavBreakpointContext, subscribe: true }),
    decorators_js.state()
], SitMainnavDropdown.prototype, "_breakpointReached", void 0);
tslib.__decorate([
    context.consume({ context: mainnavContext.MainnavExpandedContext, subscribe: true }),
    decorators_js.state()
], SitMainnavDropdown.prototype, "expanded", void 0);
tslib.__decorate([
    decorators_js.query(".nav-link")
], SitMainnavDropdown.prototype, "navLink", void 0);
tslib.__decorate([
    decorators_js.query(".dropdown-items")
], SitMainnavDropdown.prototype, "dropdownItems", void 0);
tslib.__decorate([
    decorators_js.query(".dropdown-items a")
], SitMainnavDropdown.prototype, "menuHeaderButton", void 0);
tslib.__decorate([
    decorators_js.query(".dropdown-items span")
], SitMainnavDropdown.prototype, "menuHeaderText", void 0);
tslib.__decorate([
    decorators_js.property({ type: Boolean })
], SitMainnavDropdown.prototype, "active", void 0);
tslib.__decorate([
    decorators_js.property({ type: Boolean, reflect: true })
], SitMainnavDropdown.prototype, "disabled", void 0);
tslib.__decorate([
    decorators_js.property({ type: String })
], SitMainnavDropdown.prototype, "ariaLabel", void 0);
tslib.__decorate([
    decorators_js.queryAssignedElements({ slot: "toggler" })
], SitMainnavDropdown.prototype, "togglerNodes", void 0);
tslib.__decorate([
    decorators_js.queryAssignedElements()
], SitMainnavDropdown.prototype, "defaultNodes", void 0);

exports.SitMainnavDropdown = SitMainnavDropdown;
exports["default"] = SitMainnavDropdown;
//# sourceMappingURL=sit-mainnav-dropdown.cjs.js.map
