'use client';
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var lit = require('lit');

var css_248z = lit.css`:host([class^=second-level]) .sidenav-btn{font-weight:var(--sit-font-weight-regular);padding-left:var(--sit-padding-3-xl)}button{all:unset}.sidenav-btn{background:0;border:0;border-radius:var(--sit-border-radius-md);display:flex;font-size:var(--sit-font-size-label-md);font-weight:var(--sit-font-weight-semibold);gap:var(--sit-gap-xs);line-height:var(--sit-line-height-xs);padding:var(--sit-padding-sm) var(--sit-padding-sm) var(--sit-padding-sm) calc(var(--sit-padding-sm) + var(--sit-padding-2-xs));text-align:initial;width:100%;.caret-icon,slot[name=caret-icon]::slotted(*){margin-bottom:auto;margin-left:auto;transform:rotate(180deg);transition:all .3s ease-in-out}}.sidenav-btn:hover:not(.disabled){background-color:var(--sit-bg-translucent-subtle)}.sidenav-btn.active{color:var(--sit-color-default)}.sidenav-btn.disabled{opacity:var(--sit-opacity-40);pointer-events:none}.sidenav-btn:not(.active){.caret-icon,slot[name=caret-icon]::slotted(*){transform:rotate(0deg)}}.sidenav-btn:focus-visible:not(.disabled){background-color:var(--sit-bg-translucent-subtle)}.sidenav-btn:focus-visible:not(.disabled){outline:var(--sit-outline-focus);outline-offset:var(--sit-outline-offset-focus)}.no-menu-default::slotted(a){background:0;border:0;border-radius:var(--sit-border-radius-md);color:inherit!important;display:flex;font-size:var(--sit-font-size-label-md);font-weight:var(--sit-font-weight-semibold)!important;gap:var(--sit-gap-xs);line-height:var(--sit-line-height-xs)!important;padding:var(--sit-padding-sm) var(--sit-padding-sm) var(--sit-padding-sm) calc(var(--sit-padding-sm) + var(--sit-padding-2-xs));text-decoration:none!important}.no-menu-default::slotted(a:focus-visible){background-color:var(--sit-bg-translucent-subtle)}.no-menu-default::slotted(a:focus-visible){outline:var(--sit-outline-focus);outline-offset:var(--sit-outline-offset-focus)}:host([class^=first-level][active]) .no-menu-default::slotted(a){background-color:var(--sit-primary-surface-translucent);color:var(--sit-primary-color-emphasis)!important}:host([class^=first-level][disabled]) .no-menu-default::slotted(a){opacity:var(--sit-opacity-40);pointer-events:none}`;

exports["default"] = css_248z;
//# sourceMappingURL=sidenav-item.cjs.js.map
