/**
 * Canvas Web Components – React TypeScript Type Definitions
 *
 * Auto-generated by scripts/generateSitTypes.mjs — do not edit by hand.
 *
 * Provides typed JSX intrinsic elements for all `sit-*` custom elements so
 * that React and Next.js TypeScript projects get IntelliSense and type-safety
 * without importing the full library at runtime.
 *
 * Usage – add ONE of the following to your project's `types.d.ts`:
 *
 *   // Triple-slash reference (works in any tsconfig):
 *   /// <reference path="node_modules/@sit-canvas/canvas-web-component/sit-types.d.ts" />
 *
 *   // ES import (tsconfig must include this file via `include` or `typeRoots`):
 *   import "@sit-canvas/canvas-web-component/sit-types";
 *
 * Custom event handlers support both forms:
 *   - Kebab-case (React 19 intrinsic elements): <sit-input onsit-change={handler} />
 *   - CamelCase (@lit/react wrappers):          <SitInput onSitChange={handler} />
 */

export {};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export type SitEventHandler = (event: CustomEvent) => void;

/** Common props shared by every Canvas element */
export interface SitBaseProps extends React.HTMLAttributes<HTMLElement> {
  /** Override the CSS `class` attribute (use `className` in JSX for React) */
  class?: string;
}

// ---------------------------------------------------------------------------
// Event detail interfaces (from per-component types.d.ts)
// ---------------------------------------------------------------------------

// ── Card ─────────────────────────────────────────────────────────────

type CardImageAdjustment = "default" | "padding around" | "aspect ratio";
type CardImagePosition = "before" | "after";
type CardOrientation = "vertical" | "horizontal";

// ── Checkbox ─────────────────────────────────────────────────────────────

interface ISitCheckboxGroupChangeEventDetail {
    value: string;
}

// ── ComboBox ─────────────────────────────────────────────────────────────

interface ISitComboBoxInputEventDetail {
    displayValue: string;
}

// ── Datepicker ─────────────────────────────────────────────────────────────

type ViewEnum = "days" | "months" | "years";

// ── FileUpload ─────────────────────────────────────────────────────────────

type ISitFileUploadAddFilesEventDetail = FileList;
type ISitFileUploadChangeEventDetail = FileList;
type ISitFileUploadFilesSelectedEventDetail = FileList;
interface ISitFileUploadRemoveFileEventDetail {
    file: File;
    files: FileList;
}

// ── Pagination ─────────────────────────────────────────────────────────────

interface ISitPaginationPageChangeEventDetail {
    currentPage: number;
}

// ── Radio ─────────────────────────────────────────────────────────────

interface ISitRadioGroupChangeEventDetail {
    value: string;
}

// ── Stepper ─────────────────────────────────────────────────────────────

interface IStepMetaData {
    component: unknown;
    stepHeader: string;
    iconName?: string;
    isCompleted?: boolean;
}

// ── Switch ─────────────────────────────────────────────────────────────

interface ISitSwitchChangeEventDetail {
    checked: boolean;
}

// ---------------------------------------------------------------------------
// Component prop interfaces
// ---------------------------------------------------------------------------

// ── AccordionItem ─────────────────────────────────────────────────────────────

export interface SitAccordionItemProps extends SitBaseProps {
  /** Controls whether accordion-item is open or close */
  open?: boolean;
  /** Disables the accordion item */
  disabled?: boolean;
  /** Controls the density of the individual accordion item. This value is controlled by sit-accordion */
  density?: AccordionDensity;
  /** The aria-label attribute forwarded to the accordion item button. */
  ariaLabel?: string;
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-after-show"?: SitEventHandler;
  onSitAfterShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
  "onsit-after-hide"?: SitEventHandler;
  onSitAfterHide?: SitEventHandler;
}

// ── Accordion ─────────────────────────────────────────────────────────────

export interface SitAccordionProps extends SitBaseProps {
  /** Allows multiple accordion items to be opened at the same time */
  allowMultiple?: boolean;
  /** The variant of accordion */
  variant?: "default" | "border";
  /** The density of accordion */
  density?: "default" | "compact" | "spacious";
}

// ── AlertLink ─────────────────────────────────────────────────────────────

export interface SitAlertLinkProps extends SitBaseProps {
  /** Forwards to href attribute of anchor element */
  href?: string;
  /** Tells the browser where to open the link */
  target?: "_blank" | "_parent" | "_self" | "_top";
}

// ── Alert ─────────────────────────────────────────────────────────────

export interface SitAlertProps extends SitBaseProps {
  /** Controls the appearance of the alert */
  show?: boolean;
  /** Enables a close button that allows the user to dismiss the alert. */
  dismissible?: boolean;
  /** The alert's theme variant. */
  variant?: "info" | "success" | "danger" | "warning" | "neutral";
  /** Controls the alert visual between a lighter outline and a solid darker variant. */
  outlined?: boolean;
  /** The title of the alert. Only text is allowed */
  title?: string;
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
}

// ── Avatar ─────────────────────────────────────────────────────────────

export interface SitAvatarProps extends SitBaseProps {
  /** Image URL. Falls back to `initials`, then a generic person icon, if unset or if the image fails to load. */
  src?: string;
  /** Accessible alt text for the image. Also used (with `initials`) as the seed for the deterministic fallback-colour hash when `initials` is unset. */
  alt?: string;
  /** 1-2 letters shown when there's no image (or the image fails to load). Longer strings are used as-is -- truncate before setting this if needed. */
  initials?: string;
  /** Avatar diameter. Matches this library's xs/sm/md/lg/xl size-tier convention (see sit-icon, sit-spinner). */
  size?: "xs" | "sm" | "md" | "lg" | "xl";
  /** Status-dot state. Omit to render no dot at all. */
  status?: "online" | "away" | "offline" | undefined;
  "onsit-error"?: SitEventHandler;
  onSitError?: SitEventHandler;
}

// ── Badge ─────────────────────────────────────────────────────────────

export interface SitBadgeProps extends SitBaseProps {
  /** Controls the appearance of the dismissible badge. This prop only applies when dismissible is true */
  show?: boolean;
  /** One or more badge variant combinations.
Variants include: `primary`, `accent`, `success`, `danger`, `warning`, `cyan`, `purple`, `neutral`, `white`, `info`.

(@deprecated) The `info` variant is deprecated. Use `primary` instead. */
  variant?: "primary" | "accent" | "success" | "danger" | "warning" | "cyan" | "purple" | "neutral" | "white" | "info";
  /** Manually set the outlined state to false */
  outlined?: boolean;
  /** Manually set the dismissible state of the button to `false` */
  dismissible?: boolean;
  /** Manually enable full width */
  fullWidth?: boolean;
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
  "onsit-after-show"?: SitEventHandler;
  onSitAfterShow?: SitEventHandler;
  "onsit-after-hide"?: SitEventHandler;
  onSitAfterHide?: SitEventHandler;
}

// ── BreadcrumbItem ─────────────────────────────────────────────────────────────

export interface SitBreadcrumbItemProps extends SitBaseProps {
  /** Indicates the link matches the current location of the page. Programmatically handled by SitBreadcrumb to set this prop to true for the last breadcrumb item */
  active?: boolean;
}

// ── Breadcrumb ─────────────────────────────────────────────────────────────

export interface SitBreadcrumbProps extends SitBaseProps {
  /** The aria-label of nav element within breadcrumb component. */
  ariaLabel?: string;
}

// ── Button ─────────────────────────────────────────────────────────────

export interface SitButtonProps extends SitBaseProps {
  /** The name of the button, submitted as a name/value pair with form data only when this button is the submitter. Only works with `type="submit"`. Has no effect when the button is rendered as a link (i.e. when `href` is set). */
  name?: string;
  /** The value of the button, submitted as a name/value pair with form data only when this button is the submitter. Only works with `type="submit"`. Has no effect when the button is rendered as a link (i.e. when `href` is set). */
  value?: string;
  /** The behavior of the button with default as `type='button', `reset` resets all the controls to their initial values and `submit` submits the form data to the server */
  type?: "button" | "submit" | "reset";
  /** The "form owner" to associate the button with. If omitted, the closest containing form will be used instead. The
value of this attribute must be an id of a form in the same document or shadow root as the button. */
  form?: string;
  /** Used to override the form owner's `action` attribute. */
  formAction?: string;
  /** Used to override the form owner's `method` attribute. */
  formMethod?: "post" | "get";
  /** Used to override the form owner's `novalidate` attribute. */
  formNoValidate?: boolean;
  /** Used to override the form owner's `target` attribute. */
  formTarget?: | "_self"
    | "_blank"
    | "_parent"
    | "_top"
    | string;
  /** When set, the button will be in full width. */
  fullWidth?: boolean;
  /** Used only for SSR to indicate the presence of the `leftIcon` slot. */
  hasLeftIconSlot?: boolean;
  /** Used only for SSR to indicate the presence of the `rightIcon` slot. */
  hasRightIconSlot?: boolean;
  /** Sets the visual variants such as: `primary`, `outline`, `ghost`. The `danger` value is deprecated since v3.5.6 — use `variant="primary"` with `tone="danger"` instead. */
  variant?: "primary" | "outline" | "ghost" | "danger";
  /** Sets the visual colour of the button: `brand`, `danger`, `fixed-light`, `neutral` */
  tone?: "brand" | "danger" | "fixed-light" | "neutral";
  /** Specifies a small, medium or large button, the size is medium by default. */
  size?: "xs" | "sm" | "md" | "lg";
  /** Manually set the visual state of the button to `:active` */
  active?: boolean;
  /** The disabled state of the button */
  disabled?: boolean;
  /** When set, the underlying button will be rendered as an `<a>` with this `href` instead of a `<button>`. */
  href?: string;
  /** Where to display the linked URL, as the name for a browsing context. Forwards to the HTMLAnchor target attribute */
  target?: "_blank" | "_parent" | "_self" | "_top";
  /** Tells the browser to download the linked file as this filename. Only used when `href` is set. */
  download?: string;
  /** The aria-label attribute to passed to button element when necessary */
  ariaLabel?: string;
  /** When true, shows a loading spinner */
  loading?: boolean;
  "onsit-blur"?: SitEventHandler;
  onSitBlur?: SitEventHandler;
  "onsit-focus"?: SitEventHandler;
  onSitFocus?: SitEventHandler;
}

// ── CheckboxGroup ─────────────────────────────────────────────────────────────

export interface SitCheckboxGroupProps extends SitBaseProps {
  /** The checkbox group's label */
  label?: string;
  /** Feedback text for error state when validated */
  invalidFeedback?: string;
  /** Allows invalidFeedback, invalid styles to be visible. When SitCheckboxGroup is used, it overrides the value of hasFeedback on SitCheckbox with its own value. */
  hasFeedback?: boolean;
  /** The checkbox group's hint text */
  hintText?: string;
  /** Makes the checkbox group a required field. Only available for when multiselect is true */
  required?: boolean;
  /** Disables native and sit validation for the checkbox group. */
  noValidate?: boolean;
  /** Consolidates the values of its child checked checkboxes into a single string with semi-colon delimiter. Only available when required is true */
  value?: string;
  /** Returns the ValidityState object */
  validity?: ValidityState;
  /** Returns the validation message based on the ValidityState */
  validationMessage?: unknown;
  /** The input's name attribute */
  name?: string;
  /** Disables the input. */
  disabled?: boolean;
  /** Marks the component as invalid. Replace the pseudo :invalid selector for absent in custom elements */
  invalid?: boolean;
  "onsit-change"?: SitEventHandler;
  onSitChange?: SitEventHandler;
  "onsit-invalid"?: SitEventHandler;
  onSitInvalid?: SitEventHandler;
  "onsit-valid"?: SitEventHandler;
  onSitValid?: SitEventHandler;
}

// ── Checkbox ─────────────────────────────────────────────────────────────

export interface SitCheckboxProps extends SitBaseProps {
  /** Value of the HTML form control. Primarily used to differentiate a list of related checkboxes that have the same name. */
  value?: string;
  /** Draws the checkbox in a checked state. */
  checked?: boolean;
  /** Allows invalidFeedback, invalid and valid styles to be visible with the input */
  hasFeedback?: "style" | "text" | "both";
  /** Marks the checkbox input as indeterminate , with indeterminate logo */
  indeterminate?: boolean;
  /** Makes the checkbox a required field. */
  required?: boolean;
  /** Disables native and sit validation for the checkbox. */
  noValidate?: boolean;
  /** Feedback text for error state when validated */
  invalidFeedback?: string;
  /** Returns the ValidityState object */
  validity?: ValidityState;
  /** Returns the validation message based on the ValidityState */
  validationMessage?: unknown;
  /** The input's label */
  label?: string;
  /** The input's hint text */
  hintText?: string;
  /** The input's name attribute */
  name?: string;
  /** Disables the input. */
  disabled?: boolean;
  /** Marks the component as invalid. Replace the pseudo :invalid selector for absent in custom elements */
  invalid?: boolean;
  "onsit-change"?: SitEventHandler;
  onSitChange?: SitEventHandler;
  "onsit-blur"?: SitEventHandler;
  onSitBlur?: SitEventHandler;
  "onsit-focus"?: SitEventHandler;
  onSitFocus?: SitEventHandler;
  "onsit-check"?: SitEventHandler;
  onSitCheck?: SitEventHandler;
  "onsit-uncheck"?: SitEventHandler;
  onSitUncheck?: SitEventHandler;
  "onsit-invalid"?: SitEventHandler;
  onSitInvalid?: SitEventHandler;
  "onsit-valid"?: SitEventHandler;
  onSitValid?: SitEventHandler;
}

// ── Card ─────────────────────────────────────────────────────────────

export interface SitCardProps extends SitBaseProps {
  /** Sets the image position of the card. Available options: `before`, `after` */
  imagePosition?: CardImagePosition;
  /** Controls how the image is sized and aligned within the card. Available options: `default`, `padding around`, `aspect ratio` */
  imageAdjustment?: CardImageAdjustment;
  /** Used only for SSR to indicate the presence of the `image` slot. */
  hasImageSlot?: boolean;
  /** Used only for SSR to indicate the presence of the `icon` slot. */
  hasIconSlot?: boolean;
  /** Used only for SSR to indicate the presence of the `upper` slot. */
  hasUpperSlot?: boolean;
  /** Removes the card's internal padding when set to true. */
  noPadding?: boolean;
  /** Extends the link passed in either `footer` or `link`(deprecated) slot. */
  stretchedLink?: boolean;
  /** Disables the card */
  disabled?: boolean;
  /** When true, hides the default border of the card. */
  hideBorder?: boolean;
  /** When true, applies a tinted background color to the card. */
  tinted?: boolean;
  /** Sets the orientation of the card. Available options: `vertical`, `horizontal` */
  orientation?: CardOrientation;
}

// ── CloseButton ─────────────────────────────────────────────────────────────

export interface SitCloseButtonProps extends SitBaseProps {
  /** Specifies a large or small button */
  size?: "sm" | "md";
  /** The tone of the close button */
  tone?: "default" | "fixed-dark" | "fixed-light";
  /** Disables the close button, preventing click events */
  disabled?: boolean;
}

// ── ComboBoxOption ─────────────────────────────────────────────────────────────

export interface SitComboBoxOptionProps extends SitBaseProps {
  /** Disables the Item */
  disabled?: boolean;
  /** The value of the option item */
  value?: string;
}

// ── ComboBox ─────────────────────────────────────────────────────────────

export interface SitComboBoxProps extends SitBaseProps {
  /** If true, renders multiple checkbox selection items. If false, single-select. */
  multiSelect?: boolean;
  /** If true, renders badge that fills width of combobox */
  badgeFullWidth?: boolean;
  /** If true, a clear button will be enabled on focus */
  clearable?: boolean;
  /** Disables native and sit validation for the combo box. */
  noValidate?: boolean;
  /** Enables the asynchronous behaviour of a combo box. When true, filterFunction is ignored and filtering is done remotely. */
  async?: boolean;
  /** When filtering remotely and there are no results, set this to true to enable no options feedback on the menu. Applicable for async combo box only. */
  emptyMenuAsync?: boolean;
  /** Number of pixels from the bottom of the menu at which the sit-scroll-end event fires. */
  scrollBottomOffset?: number;
  /** The function used to filter the menu list, given the user's input value. */
  filterFunction?: (inputValue: string, item: SitComboBoxOptionData) => boolean;
  /** The input's label */
  label?: string;
  /** The input's hint text below the label */
  hintText?: string;
  /** The input's name attribute */
  name?: string;
  /** The input's placeholder text. */
  placeholder?: string;
  /** Autofocus the input */
  autofocus?: boolean;
  /** Disables the input. */
  disabled?: boolean;
  /** Makes the input a required field. */
  required?: boolean;
  /** Sets the loading state of the component */
  loading?: boolean;
  /** IMPORTANT:
We still expose `.value` externally, but this is now the underlying ID or data
(e.g. 1, 2, 'abc', ...), not the label that appears in the input box. */
  value?: string;
  displayValue?: string;
  /** Allows invalidFeedback, invalid and valid styles to be visible with the input */
  hasFeedback?: boolean;
  /** Feedback text for error state when validated */
  invalidFeedback?: string;
  /** Marks the component as invalid. Replace the pseudo :invalid selector. */
  invalid?: boolean;
  /** Controlling of autocomplete behaviour */
  autocomplete?: string;
  /** The list of items to display in the dropdown.
`interface SitComboBoxItemData {
label: string;
value: string;
}` */
  menuList?: SitOptionData[];
  /** Returns the ValidityState object */
  validity?: ValidityState;
  /** Returns the validation message based on the ValidityState */
  validationMessage?: string;
  /** Additional configuration to pass to Floating UI. */
  floatingOpts?: { placement?: Placement; middleware?: Array<Middleware> };
  hidden?: boolean;
  /** When true, dropdown menu shows on first load */
  menuIsOpen?: boolean;
  /** Makes the input readonly. */
  readonly?: boolean;
  "onsit-select"?: SitEventHandler;
  onSitSelect?: SitEventHandler;
  "onsit-change"?: SitEventHandler;
  onSitChange?: SitEventHandler;
  "onsit-input"?: (event: CustomEvent<ISitComboBoxInputEventDetail>) => void;
  onSitInput?: (event: CustomEvent<ISitComboBoxInputEventDetail>) => void;
  "onsit-focus"?: SitEventHandler;
  onSitFocus?: SitEventHandler;
  "onsit-blur"?: SitEventHandler;
  onSitBlur?: SitEventHandler;
  "onsit-invalid"?: SitEventHandler;
  onSitInvalid?: SitEventHandler;
  "onsit-valid"?: SitEventHandler;
  onSitValid?: SitEventHandler;
  "onsit-scroll-end"?: SitEventHandler;
  onSitScrollEnd?: SitEventHandler;
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-after-show"?: SitEventHandler;
  onSitAfterShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
  "onsit-after-hide"?: SitEventHandler;
  onSitAfterHide?: SitEventHandler;
}

// ── Drawer ─────────────────────────────────────────────────────────────

export interface SitDrawerProps extends SitBaseProps {
  /** Indicates whether or not the drawer is open. You can toggle this attribute to show and hide the drawer, or you can
use the `show()` and `hide()` methods and this attribute will reflect the drawer's open state. */
  open?: boolean;
  /** Defines the size of the drawer panel.
For drawers placed on the left or right (`start`/`end`), this controls the drawer's width.
For drawers placed on the top or bottom, this controls the drawer's height.
Accepts `small`, `medium`, or `large`. Defaults to `small`. */
  size?: "sm" | "md" | "lg";
  /** The direction from which the drawer will open. */
  placement?: "top" | "end" | "bottom" | "start";
  /** The accessible label for the drawer dialog. This is required for assistive technology. */
  ariaLabel?: string;
  /** By default, the drawer slides out of its containing block (usually the viewport). To make the drawer slide out of
its parent element, set this attribute and add `position: relative` to the parent. */
  contained?: boolean;
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-after-show"?: SitEventHandler;
  onSitAfterShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
  "onsit-after-hide"?: SitEventHandler;
  onSitAfterHide?: SitEventHandler;
  "onsit-initial-focus"?: SitEventHandler;
  onSitInitialFocus?: SitEventHandler;
  "onsit-request-close"?: SitEventHandler;
  onSitRequestClose?: SitEventHandler;
}

// ── Datepicker ─────────────────────────────────────────────────────────────

export interface SitDatepickerProps extends SitBaseProps {
  /** When true, adds required attribute to input element */
  required?: boolean;
  /** The datepicker input's name attribute */
  name?: string;
  /** When true, adds disabled attribute to input and button element */
  disabled?: boolean;
  /** Disables native and sit validation for the datepicker. */
  noValidate?: boolean;
  /** Sets the initial value of the datepicker. Replaces deprecated `initialValue`.
Pass in dates in this format `dd/mm/yyyy` for single mode and  `dd/mm/yyyy - dd/mm/yyyy` for range mode
For example, `value="22/12/2023"` for single mode or `value="22/12/2023 - 25/12/2023"` for range mode */
  value?: string;
  /** Deprecated since v3.3.0 in favour of `value`.
The initial value of DatePicker on first load for single &
range mode as array of string. eg.'["22/12/2023"]' for single &
'["22/12/2023","25/12/2023"]' for range respectively @deprecated */
  initialValue?: string[];
  /** ISO date string to set the lowest allowable date value. e.g. "2016-05-19T12:00:00.000Z" */
  minDate?: string;
  /** ISO date string to set the highest allowable date value. e.g. "2016-05-19T12:00:00.000Z" */
  maxDate?: string;
  /** Changes DatePicker to single date selection or range date selection */
  mode?: "single" | "range";
  /** Feedback text for error state when date input is invalid */
  invalidFeedback?: string;
  /** Allows invalidFeedback and invalid styles to be visible with the input */
  hasFeedback?: boolean;
  /** The datepicker input's label */
  label?: string;
  /** The datepicker input's hint text below the label */
  hintText?: string;
  /** Controls auto-flipping of menu */
  noFlip?: boolean;
  /** The drop position of menu relative to the toggle button */
  drop?: "up" | "down";
  /** Provides the date context for Calendar to present the appropriate view. Defaults to today's date */
  displayDate?: Date;
  /** Gets or sets the default value used to reset this element. The initial value corresponds to the one originally specified in the HTML that created this element. */
  defaultValue?: string;
  /** Marks the component as invalid. Replace the pseudo :invalid selector. */
  invalid?: boolean;
  /** Returns the ValidityState object */
  validity?: ValidityState;
  /** Returns the validation message based on the ValidityState */
  validationMessage?: unknown;
  /** Additional configuration to pass to Floating UI. */
  floatingOpts?: { placement?: Placement; middleware?: Array<Middleware> };
  /** When true, dropdown menu shows on first load */
  menuIsOpen?: boolean;
  /** Makes the input readonly. */
  readonly?: boolean;
  "onsit-change-date"?: SitEventHandler;
  onSitChangeDate?: SitEventHandler;
  "onsit-invalid"?: SitEventHandler;
  onSitInvalid?: SitEventHandler;
  "onsit-valid"?: SitEventHandler;
  onSitValid?: SitEventHandler;
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-after-show"?: SitEventHandler;
  onSitAfterShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
  "onsit-after-hide"?: SitEventHandler;
  onSitAfterHide?: SitEventHandler;
}

// ── Divider ─────────────────────────────────────────────────────────────

export interface SitDividerProps extends SitBaseProps {
  /** Sets the orientation of divider to vertical. Defaults to horizontal */
  orientation?: "horizontal" | "vertical";
  /** Sets the orientation of divider to vertical. Defaults to false */
  thickness?: "thin" | "thick" | "thicker";
}

// ── DescriptionListGroup ─────────────────────────────────────────────────────────────

export interface SitDescriptionListGroupProps extends SitBaseProps {
  /** When true, adds a border around the entire group. */
  bordered?: boolean;
  /** When true, the description lists are displayed in a stacked layout. */
  stacked?: boolean;
  /** Used only for SSR to indicate the presence of the `title` slot. */
  hasTitleSlot?: boolean;
  /** Used only for SSR to indicate the presence of the `description` slot. */
  hasDescriptionSlot?: boolean;
}

// ── DescriptionList ─────────────────────────────────────────────────────────────

export interface SitDescriptionListProps extends SitBaseProps {
  /** Makes the label and the data stacked */
  stacked?: boolean;
  /** Changes the border bottom styles for bordered description list group */
  bordered?: boolean;
}

// ── DropdownItem ─────────────────────────────────────────────────────────────

export interface SitDropdownItemProps extends SitBaseProps {
  /** when true, sets the active stylings of dropdown item */
  active?: boolean;
  /** Disables the SitMainnavItem */
  disabled?: boolean;
  /** Forwards aria-label to the inner clickable element for accessibility */
  ariaLabel?: string;
}

// ── Dropdown ─────────────────────────────────────────────────────────────

export interface SitDropdownProps extends SitBaseProps {
  /** Controls auto-flipping of menu */
  noFlip?: boolean;
  /** When true, aligns right edge of menu with right edge of button */
  menuAlignRight?: boolean;
  /** The drop position of menu relative to the toggle button */
  drop?: "left" | "right" | "up" | "down";
  hidden?: boolean;
  /** Additional configuration to pass to Floating UI. */
  floatingOpts?: { placement?: Placement; middleware?: Array<Middleware> };
  /** When true, dropdown menu shows on first load */
  menuIsOpen?: boolean;
  /** Disables the dropdown toggle */
  disabled?: boolean;
  /** Makes the input readonly. */
  readonly?: boolean;
  "onsit-select"?: SitEventHandler;
  onSitSelect?: SitEventHandler;
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-after-show"?: SitEventHandler;
  onSitAfterShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
  "onsit-after-hide"?: SitEventHandler;
  onSitAfterHide?: SitEventHandler;
}

// ── FileUpload ─────────────────────────────────────────────────────────────

export interface SitFileUploadProps extends SitBaseProps {
  /** Allows multiple files to be listed for uploading */
  multiple?: boolean;
  /** Specify the acceptable file type */
  accept?: string;
  /** Allows invalidFeedback, invalid and valid styles to be visible with the input */
  hasFeedback?: boolean;
  /** Feedback text for error state when validated */
  invalidFeedback?: string;
  /** Makes the input as a required field. */
  required?: boolean;
  /** Variant of the file upload component: "default" or "drag-and-drop" */
  variant?: "default" | "drag-and-drop";
  /** An accessible label for the file upload button. Defaults to "Choose files" if not set. */
  ariaLabel?: string;
  /** Disables native and sit validation for the component. Use this when you want to do custom validation */
  noValidate?: boolean;
  /** Returns the ValidityState object */
  validity?: ValidityState;
  /** Returns the validation message based on the ValidityState */
  validationMessage?: string;
  /** Returns files selected for upload */
  files?: File[];
  /** The input's label */
  label?: string;
  /** The input's hint text */
  hintText?: string;
  /** The input's name attribute */
  name?: string;
  /** Disables the input. */
  disabled?: boolean;
  /** Marks the component as invalid. Replace the pseudo :invalid selector for absent in custom elements */
  invalid?: boolean;
  "onsit-files-selected"?: (event: CustomEvent<ISitFileUploadFilesSelectedEventDetail>) => void;
  onSitFilesSelected?: (event: CustomEvent<ISitFileUploadFilesSelectedEventDetail>) => void;
  "onsit-add-files"?: (event: CustomEvent<ISitFileUploadAddFilesEventDetail>) => void;
  onSitAddFiles?: (event: CustomEvent<ISitFileUploadAddFilesEventDetail>) => void;
  "onsit-remove-file"?: (event: CustomEvent<ISitFileUploadRemoveFileEventDetail>) => void;
  onSitRemoveFile?: (event: CustomEvent<ISitFileUploadRemoveFileEventDetail>) => void;
  "onsit-change"?: (event: CustomEvent<ISitFileUploadChangeEventDetail>) => void;
  onSitChange?: (event: CustomEvent<ISitFileUploadChangeEventDetail>) => void;
}

// ── FooterItem ─────────────────────────────────────────────────────────────

export interface SitFooterItemProps extends SitBaseProps {
  /** Sets the color tone of the footer item. Inherited from the parent sit-footer. */
  tone?: "fixed-dark" | "neutral";
}

// ── Footer ─────────────────────────────────────────────────────────────

export interface SitFooterProps extends SitBaseProps {
  /** Sets copyrightLiner of SitFooter */
  copyrightLiner?: string;
  /** href link for contacts */
  contactHref?: string;
  /** href link for feedback */
  feedbackHref?: string;
  /** href link for faq (optional) */
  faqHref?: string;
  /** href link for sitemap (optional) */
  sitemapHref?: string;
  /** href link for privacy statement */
  privacyHref?: string;
  /** href link for terms of use */
  termsOfUseHref?: string;
  /** Sets the layout context of the footer. Use "sidebar" when the footer is alongside a collapsible or persistent sidebar. Overlay sidebars should use "default". */
  layout?: "default" | "sidebar";
  /** Sets the color tone of the footer. Use "neutral" for light backgrounds (e.g. sidebar layouts). */
  tone?: "fixed-dark" | "neutral";
  /** Used only for SSR to indicate the presence of the `default` slot. */
  hasDefaultSlot?: boolean;
  /** Used only for SSR to indicate the presence of the `title` slot. */
  hasTitleSlot?: boolean;
  /** Used only for SSR to indicate the presence of the `description` slot. */
  hasDescriptionSlot?: boolean;
  /** Used only for SSR to indicate the presence of the `items` slot. */
  hasItemsSlot?: boolean;
}

// ── IconButton ─────────────────────────────────────────────────────────────

export interface SitIconButtonProps extends SitBaseProps {
  /** The name of the icon from sit icon library */
  name?: string;
  /** Sets the visual variants such as: `primary`, `outline`, `ghost`. The `danger` value is deprecated since v3.5.6 — use `variant="primary"` with `tone="danger"` instead. */
  variant?: "primary" | "outline" | "ghost" | "danger";
  /** Sets the visual colour of the button: `brand`, `danger`, `fixed-light`, `neutral` */
  tone?: "brand" | "danger" | "fixed-light" | "neutral";
  /** Specifies a small, medium or large button, the size is medium by default. */
  size?: "xs" | "sm" | "md" | "lg";
  /** Manually set the visual state of the button to `:active` */
  active?: boolean;
  /** The disabled state of the button */
  disabled?: boolean;
  /** When set, the underlying button will be rendered as an `<a>` with this `href` instead of a `<button>`. */
  href?: string;
  /** Where to display the linked URL, as the name for a browsing context. Forwards to the HTMLAnchor target attribute */
  target?: "_blank" | "_parent" | "_self" | "_top";
  /** Tells the browser to download the linked file as this filename. Only used when `href` is set. */
  download?: string;
  /** The aria-label attribute to passed to button element when necessary */
  ariaLabel?: string;
  /** When true, shows a loading spinner */
  loading?: boolean;
  "onsit-blur"?: SitEventHandler;
  onSitBlur?: SitEventHandler;
  "onsit-focus"?: SitEventHandler;
  onSitFocus?: SitEventHandler;
}

// ── IconCard ─────────────────────────────────────────────────────────────

export interface SitIconCardProps extends SitBaseProps {
  /** Removes the card's internal padding when set to true. */
  noPadding?: boolean;
  /** Extends the link passed in either `footer` or `link`(deprecated) slot. */
  stretchedLink?: boolean;
  /** Disables the card */
  disabled?: boolean;
  /** When true, hides the default border of the card. */
  hideBorder?: boolean;
  /** When true, applies a tinted background color to the card. */
  tinted?: boolean;
  /** Sets the orientation of the card. Available options: `vertical`, `horizontal` */
  orientation?: CardOrientation;
}

// ── Icon ─────────────────────────────────────────────────────────────

export interface SitIconProps extends SitBaseProps {
  /** The name of the icon from sit icon library */
  name?: string;
  /** Specifies a small, medium or large icon, the size is medium by default. */
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "2-xl" | "3-xl";
  /** An accessible label for the icon. When set, the SVG is treated as informative. When omitted, the SVG is marked as decorative with aria-hidden="true". */
  ariaLabel?: string;
}

// ── ImageCard ─────────────────────────────────────────────────────────────

export interface SitImageCardProps extends SitBaseProps {
  /** Removes the card's internal padding when set to true. */
  noPadding?: boolean;
  /** Sets the image position of the card. Available options: `before`, `after` */
  imagePosition?: CardImagePosition;
  /** Controls how the image is sized and aligned within the card. Available options: `default`, `padding around`, `aspect ratio` */
  imageAdjustment?: CardImageAdjustment;
  /** Extends the link passed in either `footer` or `link`(deprecated) slot. */
  stretchedLink?: boolean;
  /** Disables the card */
  disabled?: boolean;
  /** When true, hides the default border of the card. */
  hideBorder?: boolean;
  /** When true, applies a tinted background color to the card. */
  tinted?: boolean;
  /** Sets the orientation of the card. Available options: `vertical`, `horizontal` */
  orientation?: CardOrientation;
}

// ── Input ─────────────────────────────────────────────────────────────

export interface SitInputProps extends SitBaseProps {
  type?: | "email"
    | "number"
    | "password"
    | "search"
    | "tel"
    | "text"
    | "time"
    | "url"
    | "datetime-local";
  /** The prefix of the input */
  prefix?: string;
  /** The suffix of the input */
  suffix?: string;
  /** Sets the minimum length of the input */
  minlength?: number;
  /** Sets the maximum length of the input */
  maxlength?: number;
  /** The input's minimum value. Only applies number input types. */
  min?: number;
  /** The input's maximum value. Only applies number input types. */
  max?: number;
  /** The input's placeholder text. */
  placeholder?: string;
  /** A pattern to validate input against. */
  pattern?: string;
  /** Autofocus the input */
  autofocus?: boolean;
  /** Makes the input readonly. */
  readonly?: boolean;
  /** Controlling of autocomplete behaviour */
  autocomplete?: string;
  /** Specifies the granularity that the value must adhere to, or the special value `any` which means no stepping is
implied, allowing any numeric value. Only applies to number input types. */
  step?: number | "any";
  /** Allows invalidFeedback, invalid and valid styles to be visible with the input */
  hasFeedback?: "style" | "text" | "both";
  /** Feedback text for error state when validated */
  invalidFeedback?: string;
  /** Gets or sets the default value used to reset this element. The initial value corresponds to the one originally specified in the HTML that created this element. */
  defaultValue?: string;
  /** Marks the component as valid. */
  valid?: boolean;
  /** Marks the component as loading. */
  loading?: boolean;
  /** Makes the input a required field. */
  required?: boolean;
  /** Disables native and sit validation for the input. */
  noValidate?: boolean;
  /** The input's value attribute. */
  value?: string;
  /** Returns the ValidityState object */
  validity?: ValidityState;
  /** Returns the validation message based on the ValidityState */
  validationMessage?: unknown;
  /** The input's label */
  label?: string;
  /** The input's hint text */
  hintText?: string;
  /** The input's name attribute */
  name?: string;
  /** Disables the input. */
  disabled?: boolean;
  /** Marks the component as invalid. Replace the pseudo :invalid selector for absent in custom elements */
  invalid?: boolean;
  "onsit-change"?: SitEventHandler;
  onSitChange?: SitEventHandler;
  "onsit-input"?: SitEventHandler;
  onSitInput?: SitEventHandler;
  "onsit-focus"?: SitEventHandler;
  onSitFocus?: SitEventHandler;
  "onsit-blur"?: SitEventHandler;
  onSitBlur?: SitEventHandler;
  "onsit-invalid"?: SitEventHandler;
  onSitInvalid?: SitEventHandler;
  "onsit-valid"?: SitEventHandler;
  onSitValid?: SitEventHandler;
}

// ── IconList ─────────────────────────────────────────────────────────────

export interface SitIconListProps extends SitBaseProps {
  /** Sets the aria-role of the sit-icon-list */
  role?: string;
  /** The size of icon list. Changes the font-size the list items */
  size?: "sm" | "md" | "lg";
}

// ── Link ─────────────────────────────────────────────────────────────

export interface SitLinkProps extends SitBaseProps {
  /** Determines the size of the link */
  size?: "xs" | "sm" | "md" | "lg";
  /** Sets the colour of the link @deprecated since 3.6.0 */
  variant?: "primary" | "danger" | "neutral" | "light" | "dark";
  /** Sets the colour of the link, replaces variant prop */
  tone?: "primary" | "danger" | "neutral" | "fixed-light" | "fixed-dark";
  /** When true, sets the active stylings of the link */
  active?: boolean;
  /** Disables the link */
  disabled?: boolean;
}

// ── MainnavDropdown ─────────────────────────────────────────────────────────────

export interface SitMainnavDropdownProps extends SitBaseProps {
  /** When true,  applies active styles on the dropdown button */
  active?: boolean;
  /** When true,  applies active styles on the dropdown button */
  disabled?: boolean;
  /** Accessible label for the dropdown's toggle button. Forwarded to the button's aria-label attribute. */
  ariaLabel?: string;
}

// ── MainnavItem ─────────────────────────────────────────────────────────────

export interface SitMainnavItemProps extends SitBaseProps {
  /** when true, sets the active stylings of the navigation item */
  active?: boolean;
  /** Disables the SitMainnavItem */
  disabled?: boolean;
}

// ── Mainnav ─────────────────────────────────────────────────────────────

export interface SitMainnavProps extends SitBaseProps {
  /** Used only for SSR to indicate the presence of the `non-collapsible` slot. */
  hasNonCollapsibleSlot?: boolean;
  /** The href link for brand logo */
  brandHref?: string;
  /** The breakpoint, below which, the Navbar will collapse. When always the Navbar will always be expanded regardless of screen size. When never, the Navbar will always be collapsed */
  expand?: "sm" | "md" | "lg" | "xl" | "xxl" | "always" | "never";
  /** When true, removes max-width constraint to allow content to stretch full screen width */
  fluid?: boolean;
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-after-show"?: SitEventHandler;
  onSitAfterShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
  "onsit-after-hide"?: SitEventHandler;
  onSitAfterHide?: SitEventHandler;
}

// ── Masthead ─────────────────────────────────────────────────────────────

export interface SitMastheadProps extends SitBaseProps {
  /** When true, removes max-width constraint to allow content to stretch full screen width */
  fluid?: boolean;
}

// ── OverflowMenu ─────────────────────────────────────────────────────────────

export interface SitOverflowMenuProps extends SitBaseProps {
  /** Specifies a large or small button */
  size?: "sm" | "md";
}

// ── Modal ─────────────────────────────────────────────────────────────

export interface SitModalProps extends SitBaseProps {
  /** Indicates whether or not the modal is open. You can use this in lieu of the show/hide methods. */
  open?: boolean;
  /** Removes the default animation when opening and closing of modal */
  noAnimation?: boolean;
  /** Specifies a small, medium, large or fullscreen modal, the size is medium by default. */
  size?: "sm" | "md" | "lg" | "xl" | "fullscreen";
  /** Used only for SSR to indicate the presence of the `footer` slot. */
  hasFooterSlot?: boolean;
  /** Removes the close button in the modal header. */
  noCloseButton?: boolean;
  "onsit-close"?: SitEventHandler;
  onSitClose?: SitEventHandler;
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
  "onsit-after-show"?: SitEventHandler;
  onSitAfterShow?: SitEventHandler;
  "onsit-after-hide"?: SitEventHandler;
  onSitAfterHide?: SitEventHandler;
}

// ── Pagination ─────────────────────────────────────────────────────────────

export interface SitPaginationProps extends SitBaseProps {
  /** Inserts the length value from a given sets of data objects */
  dataLength?: number;
  /** Sets the starting active page upon render */
  currentPage?: number;
  /** Sets the amount of data objects to be displayed per page */
  itemsPerPage?: number;
  /** Sets the variant of the pagination. */
  variant?: "default" | "number" | "button" | "description";
  /** Sets the page direction button to contain text and/or icon */
  navigation?: "button" | "icon-button";
  /** Sets the size of all page items. */
  size?: "sm" | "md";
  "onsit-page-change"?: (event: CustomEvent<ISitPaginationPageChangeEventDetail>) => void;
  onSitPageChange?: (event: CustomEvent<ISitPaginationPageChangeEventDetail>) => void;
}

// ── Popover ─────────────────────────────────────────────────────────────

export interface SitPopoverProps extends SitBaseProps {
  /** How the popover opens: on trigger click, or on trigger hover (mouseenter/mouseleave). */
  trigger?: "click" | "hover";
  /** Placement relative to the trigger. Inherited from FloatingElement; re-declared here only for its own default. */
  placement?: Placement;
  /** Prevents the popover from opening. */
  disabled?: boolean;
  /** Whether the popover is open. Reflects, so it can be read/set like `sit-modal`'s `open`. */
  open?: boolean;
  /** Accessible name for the panel (role="dialog" requires one -- axe-core's
aria-dialog-name rule caught this as a real violation when the panel had
none). Defaults to a generic but valid label rather than shipping an
accessibility violation out of the box; override with something specific
(e.g. "Account menu") whenever the trigger's own visible text doesn't
already make the panel's purpose obvious. */
  ariaLabel?: string;
  /** Additional configuration to pass to Floating UI, merged over this base's defaults. */
  floatingOpts?: { placement?: Placement; middleware?: Array<Middleware> };
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-after-show"?: SitEventHandler;
  onSitAfterShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
  "onsit-after-hide"?: SitEventHandler;
  onSitAfterHide?: SitEventHandler;
}

// ── QuantityToggle ─────────────────────────────────────────────────────────────

export interface SitQuantityToggleProps extends SitBaseProps {
  /** The input's value. Set to 0 by default */
  value?: number;
  /** Controls the incremental / decremental value of the input */
  step?: number;
  /** The input's minimum value. Only applies number input types. */
  min?: number;
  /** The input's maximum value. Only applies number input types. */
  max?: number;
  /** Allows invalidFeedback, invalid and valid styles to be visible with the input */
  hasFeedback?: "style" | "text" | "both";
  /** Feedback text for error state when validated */
  invalidFeedback?: string;
  /** Sets the quantity toggle as readonly */
  readonly?: boolean;
  /** Gets or sets the default value used to reset this element. The initial value corresponds to the one originally specified in the HTML that created this element. */
  defaultValue?: number;
  /** Returns the ValidityState object */
  validity?: ValidityState;
  /** Returns the validation message based on the ValidityState */
  validationMessage?: unknown;
  /** The input's label */
  label?: string;
  /** The input's hint text */
  hintText?: string;
  /** The input's name attribute */
  name?: string;
  /** Disables the input. */
  disabled?: boolean;
  /** Marks the component as invalid. Replace the pseudo :invalid selector for absent in custom elements */
  invalid?: boolean;
  "onsit-change"?: SitEventHandler;
  onSitChange?: SitEventHandler;
  "onsit-input"?: SitEventHandler;
  onSitInput?: SitEventHandler;
}

// ── ProgressBar ─────────────────────────────────────────────────────────────

export interface SitProgressBarProps extends SitBaseProps {
  /** The background color of the progress bar. Available options: `primary`, `neutral` */
  variant?: "primary" | "neutral";
  /** The current progress as a percentage, from 0 to 100. */
  value?: number;
  /** Sets the minimun aria range for assistive devices.

The aria-valuemin attribute defines the minimun allowed value for a range widget. */
  ariamin?: number;
  /** Sets the maximum aria range for assistive devices.

The aria-valuemax attribute defines the maximum allowed value for a range widget. */
  ariamax?: number;
  /** Sets the aria label for assistive devices. */
  ariaLabel?: string;
  arialabel?: string;
  /** Add label on top of progress bar */
  label?: string;
}

// ── RadioGroup ─────────────────────────────────────────────────────────────

export interface SitRadioGroupProps extends SitBaseProps {
  /** The selected value of the control. */
  value?: string;
  /** Feedback text for error state when validated */
  invalidFeedback?: string;
  /** Allows invalidFeedback, invalid and valid styles to be visible with the input */
  hasFeedback?: boolean;
  /** Makes the input as a required field. */
  required?: boolean;
  /** Disables native and sit validation for the radio group. */
  noValidate?: boolean;
  /** Automatically focuses the selected radio input in the group when it becomes checked. */
  autofocus?: boolean;
  /** Returns the ValidityState object */
  validity?: ValidityState;
  /** Returns the validation message based on the ValidityState */
  validationMessage?: unknown;
  /** The input's label */
  label?: string;
  /** The input's hint text */
  hintText?: string;
  /** The input's name attribute */
  name?: string;
  /** Disables the input. */
  disabled?: boolean;
  /** Marks the component as invalid. Replace the pseudo :invalid selector for absent in custom elements */
  invalid?: boolean;
  "onsit-change"?: (event: CustomEvent<ISitRadioGroupChangeEventDetail>) => void;
  onSitChange?: (event: CustomEvent<ISitRadioGroupChangeEventDetail>) => void;
  "onsit-invalid"?: SitEventHandler;
  onSitInvalid?: SitEventHandler;
  "onsit-valid"?: SitEventHandler;
  onSitValid?: SitEventHandler;
}

// ── Radio ─────────────────────────────────────────────────────────────

export interface SitRadioProps extends SitBaseProps {
  /** Draws the radio in a checked state. When used with SitRadioGroup, the value prop of SitRadioGroup overrides the checked prop */
  checked?: boolean;
  /** The radio's value attribute. */
  value?: string;
  /** Disables the radio. */
  disabled?: boolean;
  /** Marks the radio input as invalid. Replace the pseudo :invalid selector for absent in custom elements */
  invalid?: boolean;
  /** Automatically focuses the radio input when it becomes checked. */
  autofocus?: boolean;
  "onsit-focus"?: SitEventHandler;
  onSitFocus?: SitEventHandler;
  "onsit-blur"?: SitEventHandler;
  onSitBlur?: SitEventHandler;
}

// ── SelectOption ─────────────────────────────────────────────────────────────

export interface SitSelectOptionProps extends SitBaseProps {
  /** Disables the Item */
  disabled?: boolean;
  /** The value of the option item */
  value?: string;
}

// ── Select ─────────────────────────────────────────────────────────────

export interface SitSelectProps extends SitBaseProps {
  /** Disables native and sit validation for the select. */
  noValidate?: boolean;
  /** The input's label */
  label?: string;
  /** The input's hint text below the label */
  hintText?: string;
  /** The input's name attribute */
  name?: string;
  /** The input's placeholder text. */
  placeholder?: string;
  /** Autofocus the input */
  autofocus?: boolean;
  /** Disables the input. */
  disabled?: boolean;
  /** Makes the input a required field. */
  required?: boolean;
  /** Sets the loading state of the component */
  loading?: boolean;
  /** IMPORTANT:
We still expose `.value` externally, but this is now the underlying ID or data
(e.g. 1, 2, 'abc', ...), not the label that appears in the input box. */
  value?: string;
  displayValue?: string;
  /** Allows invalidFeedback, invalid and valid styles to be visible with the input */
  hasFeedback?: boolean;
  /** Feedback text for error state when validated */
  invalidFeedback?: string;
  /** Marks the component as invalid. Replace the pseudo :invalid selector. */
  invalid?: boolean;
  /** Controlling of autocomplete behaviour */
  autocomplete?: string;
  /** The list of items to display in the dropdown.
`interface SitComboBoxItemData {
label: string;
value: string;
}` */
  menuList?: SitOptionData[];
  /** Returns the ValidityState object */
  validity?: ValidityState;
  /** Returns the validation message based on the ValidityState */
  validationMessage?: string;
  /** Additional configuration to pass to Floating UI. */
  floatingOpts?: { placement?: Placement; middleware?: Array<Middleware> };
  hidden?: boolean;
  /** When true, dropdown menu shows on first load */
  menuIsOpen?: boolean;
  /** Makes the input readonly. */
  readonly?: boolean;
  "onsit-select"?: SitEventHandler;
  onSitSelect?: SitEventHandler;
  "onsit-change"?: SitEventHandler;
  onSitChange?: SitEventHandler;
  "onsit-focus"?: SitEventHandler;
  onSitFocus?: SitEventHandler;
  "onsit-blur"?: SitEventHandler;
  onSitBlur?: SitEventHandler;
  "onsit-invalid"?: SitEventHandler;
  onSitInvalid?: SitEventHandler;
  "onsit-valid"?: SitEventHandler;
  onSitValid?: SitEventHandler;
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-after-show"?: SitEventHandler;
  onSitAfterShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
  "onsit-after-hide"?: SitEventHandler;
  onSitAfterHide?: SitEventHandler;
}

// ── SidebarGroup ─────────────────────────────────────────────────────────────

export interface SitSidebarGroupProps extends SitBaseProps {
  /** Reports the visibility state of the submenu for nested groups.
Returns true when the submenu is displayed showing child items, false when hidden.
Only applicable for nested groups (level 2+). Root-level groups use drawer overlay instead. */
  showMenu?: boolean;
  /** The display title/label for the sidebar element.
Shown in the UI and used for accessibility labels (aria-label). */
  title?: string;
  /** The unique name identifier for the sidebar element.
Used to identify selections in sit-select events and manage active states.
Should be unique among siblings in the same navigation level. */
  name?: string;
}

// ── SidebarItem ─────────────────────────────────────────────────────────────

export interface SitSidebarItemProps extends SitBaseProps {
  /** The display title/label for the sidebar element.
Shown in the UI and used for accessibility labels (aria-label). */
  title?: string;
  /** The unique name identifier for the sidebar element.
Used to identify selections in sit-select events and manage active states.
Should be unique among siblings in the same navigation level. */
  name?: string;
}

// ── SidebarSection ─────────────────────────────────────────────────────────────

export interface SitSidebarSectionProps extends SitBaseProps {
  /** The display title/label for the sidebar section header.
Always visible in the sidebar, used to group related items. */
  title?: string;
  /** Controls whether the section content is expanded or collapsed.
When true, the section content is hidden but the section header remains visible.
Only applicable when the section is collapsible. */
  collapsed?: boolean;
  /** Enables a collapsible section header with expand/collapse toggle functionality.
When true, users can click the header to toggle section visibility.
When false, the section header is display-only and not interactive. */
  collapsible?: boolean;
  /** When true, renders a divider below the section content to visually separate it from the next section. */
  separator?: boolean;
  /** The unique name identifier for the sidebar element.
Used to identify selections in sit-select events and manage active states.
Should be unique among siblings in the same navigation level. */
  name?: string;
}

// ── Sidebar ─────────────────────────────────────────────────────────────

export interface SitSidebarProps extends SitBaseProps {
  /** Controls whether the sidebar is collapsed or expanded to save screen space.
When true, sidebar displays icon-only mode for root items. When false, full labels and content are shown.
On mobile devices (width <= 576px), this is automatically toggled based on screen size.
Collapsing propagates to child items, affecting label visibility and spacing. */
  collapsed?: boolean;
  /** The name of the currently active sidebar item or group for programmatic control.
Setting this property programmatically selects the item with the matching `name` attribute.
Automatically expands parent groups to reveal nested items and syncs the active state throughout the hierarchy.
Clearing this property (setting to empty string) deselects all items. */
  active?: string;
  /** Shows a scrim/overlay background behind the drawer or sidebar in overlay mode.
When true, displays a semi-transparent dark overlay behind the drawer to focus user attention.
Only visible when drawer is open or in overlay mode with sidebar not collapsed. */
  scrim?: boolean;
  /** Controls the sidebar's collapse behaviour.
- `"collapsible"` (default): shows a toggle button that collapses/expands the sidebar.
- `"persistent"`: sidebar is always visible and cannot be collapsed.
- `"overlay"`: sidebar slides over the content as a drawer on smaller viewports. */
  variant?: "collapsible" | "persistent" | "overlay";
  /** Accessible label for the sidebar navigation landmark.
Passed to the `<nav>` element's `aria-label` attribute so screen readers can distinguish
this sidebar from other navigation regions on the page (e.g. a top mainnav).
Override when your page uses a more specific term (e.g. `"Dashboard navigation"`). */
  ariaLabel?: string;
}

// ── SidenavItem ─────────────────────────────────────────────────────────────

export interface SitSidenavItemProps extends SitBaseProps {
  body?: HTMLElement;
  /** when true, toggles the sidenav-item to open on first load and set the active stylings. */
  active?: boolean;
  /** Disables the SitSidenavItem */
  disabled?: boolean;
  /** Accessible label for the sidenav item's menu button. Forwarded to the button's aria-label attribute. */
  ariaLabel?: string;
  "onsit-toggle"?: SitEventHandler;
  onSitToggle?: SitEventHandler;
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-after-show"?: SitEventHandler;
  onSitAfterShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
  "onsit-after-hide"?: SitEventHandler;
  onSitAfterHide?: SitEventHandler;
}

// ── SidenavLink ─────────────────────────────────────────────────────────────

export interface SitSidenavLinkProps extends SitBaseProps {
  /** when true, sets the active stylings of .nav-link */
  active?: boolean;
  /** Disables the SitMainnavItem */
  disabled?: boolean;
}

// ── Sidenav ─────────────────────────────────────────────────────────────

export interface SitSidenavProps extends SitBaseProps {
  /** Apply position sticky to the sidenav */
  sticky?: boolean;
}

// ── Skeleton ─────────────────────────────────────────────────────────────

export interface SitSkeletonProps extends SitBaseProps {
  /** Sets the width of skeleton. Pass value in string with length units like pixels or percentage. */
  width?: string;
  /** Sets the height of skeleton. Pass value in string with length units like pixels or percentage. */
  height?: string;
  /** Sets the border radius of skeleton. Pass value in string with length units like pixels and percentage
When `row` is defined, the borderRadius is forwarded down to the border radius of each skeleton row */
  borderRadius?: string;
  /** Sets the number of rows within the given height of the skeleton.
By default, the height of each row is auto-sized by taking the height of the skeleton divided by the number of rows and
taking into account that there is a gap set by root css variable `--sit-gap-xs` between each rows */
  rows?: number;
  /** Adds a sheening animated effect to the skeleton */
  sheen?: boolean;
}

// ── Step ─────────────────────────────────────────────────────────────

export interface SitStepProps extends SitBaseProps {
  /** The header text for the step */
  stepHeader?: string;
  /** Optional icon name to display instead of step number */
  iconName?: string | undefined;
  /** Optional component reference associated with this step. Retrievable via `sit-stepper.getComponent()`. */
  component?: unknown;
  /** Whether this step is clickable */
  clickable?: boolean;
  /** Whether this step is currently active */
  active?: boolean;
  /** Whether this step is currently disabled */
  disabled?: boolean;
  /** Whether this step is completed */
  completed?: boolean;
}

// ── Stepper ─────────────────────────────────────────────────────────────

export interface SitStepperProps extends SitBaseProps {
  /** The metadata of stepper, type `IStepMetaData`. Deprecated: use sit-step child components instead. */
  steps?: IStepMetaData[];
  /** The current state of active step. Defaults to 0 */
  activeStep?: number;
  /** The orientation of stepper. By default, the stepper is of horizontal orientation */
  orientation?: "horizontal" | "vertical";
  /** When true, the stepper's steps will be clickable */
  clickable?: boolean;
  /** When true, the stepper's steps can only be clicked in a linear manner */
  linear?: boolean;
  "onsit-next-step"?: SitEventHandler;
  onSitNextStep?: SitEventHandler;
  "onsit-previous-step"?: SitEventHandler;
  onSitPreviousStep?: SitEventHandler;
  "onsit-last-step"?: SitEventHandler;
  onSitLastStep?: SitEventHandler;
  "onsit-first-step"?: SitEventHandler;
  onSitFirstStep?: SitEventHandler;
  "onsit-arrived"?: SitEventHandler;
  onSitArrived?: SitEventHandler;
  "onsit-reset"?: SitEventHandler;
  onSitReset?: SitEventHandler;
}

// ── Spinner ─────────────────────────────────────────────────────────────

export interface SitSpinnerProps extends SitBaseProps {
  /** The variant of spinner. Deprecated in favor of `tone` @deprecated */
  variant?: "primary" | "neutral";
  /** The color tones of spinner, replaces variant prop */
  tone?: "brand" | "neutral" | "inverse" | "fixed-light" | "fixed-dark";
  /** Specifies a small, medium or large button, the size is medium by default. */
  size?: "xs" | "sm" | "md" | "lg" | "xl";
  /** Text label of the spinner */
  label?: string;
  /** Orientation of label relative to the spinner */
  orientation?: "horizontal" | "vertical";
}

// ── SubnavItem ─────────────────────────────────────────────────────────────

export interface SitSubnavItemProps extends SitBaseProps {
  /** when true, sets the active stylings of the navigation item */
  active?: boolean;
  /** Disables the SitSubnavItem */
  disabled?: boolean;
}

// ── Subnav ─────────────────────────────────────────────────────────────

export interface SitSubnavProps extends SitBaseProps {
  /** Used only for SSR to indicate the presence of the `actions` slot. */
  hasActionsSlot?: boolean;
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-after-show"?: SitEventHandler;
  onSitAfterShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
  "onsit-after-hide"?: SitEventHandler;
  onSitAfterHide?: SitEventHandler;
}

// ── Switch ─────────────────────────────────────────────────────────────

export interface SitSwitchProps extends SitBaseProps {
  /** The size of the switch. By default, it is small size */
  size?: "sm" | "md" | "lg";
  /** When enabled, icon appears in the switch */
  icon?: boolean;
  /** Draws the switch in a checked state. */
  checked?: boolean;
  /** Disables the switch (so the user can't check / uncheck it). */
  disabled?: boolean;
  /** Used only for SSR to indicate the presence of the `default` slot. */
  hasDefaultSlot?: boolean;
  /** Used only for SSR to indicate the presence of the `leftLabel` slot. */
  hasLeftLabelSlot?: boolean;
  "onsit-change"?: (event: CustomEvent<ISitSwitchChangeEventDetail>) => void;
  onSitChange?: (event: CustomEvent<ISitSwitchChangeEventDetail>) => void;
}

// ── SystemBannerItem ─────────────────────────────────────────────────────────────

export interface SitSystemBannerItemProps extends SitBaseProps {
  /** Used only for SSR to indicate the presence of the `action` slot. */
  hasActionSlot?: boolean;
  /** Disables the action link that appears when text content is clamped */
  noClampAction?: boolean;
  "onsit-show-more"?: SitEventHandler;
  onSitShowMore?: SitEventHandler;
}

// ── SystemBanner ─────────────────────────────────────────────────────────────

export interface SitSystemBannerProps extends SitBaseProps {
  /** Controls the appearance of the alert */
  show?: boolean;
  /** Enables a close button that allows the user to dismiss the alert. */
  dismissible?: boolean;
  /** Disables the action link that appears when text content is clamped */
  noClampAction?: boolean;
  /** When true, removes max-width constraint to allow content to stretch full screen width */
  fluid?: boolean;
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
}

// ── TabGroup ─────────────────────────────────────────────────────────────

export interface SitTabGroupProps extends SitBaseProps {
  /** The variant of tabs. Controls the visual styles of all `sit-tabs` in its slot. It also sets the variant atttribute of `sit-tab` */
  variant?: "underlined" | "solid";
  /** The orientation of tabs. Controls the orientation of all `sit-tabs` in its slot. It also sets the orientation attribute of `sit-tab` */
  orientation?: "horizontal" | "vertical";
  /** The density of tabs. Controls the density of all `sit-tabs` in its slot. It also sets the density attribute of `sit-tab` */
  density?: "compact" | "default";
  "onsit-tab-show"?: SitEventHandler;
  onSitTabShow?: SitEventHandler;
  "onsit-tab-hide"?: SitEventHandler;
  onSitTabHide?: SitEventHandler;
}

// ── TabPanel ─────────────────────────────────────────────────────────────

export interface SitTabPanelProps extends SitBaseProps {
  /** The tab panel's name. */
  name?: string;
  /** When true, the tab panel will be shown. When used with tab-group, this property is already being managed */
  active?: boolean;
}

// ── Tab ─────────────────────────────────────────────────────────────

export interface SitTabProps extends SitBaseProps {
  /** The name of the tab panel this tab is associated with. The panel must be located in the same tab group. */
  panel?: string;
  /** Draws the tab in an active state. When used with tab group, this state is already managed. Use it to set the initial active tab on first load of page */
  active?: boolean;
  /** When true, sets tab to disabled state */
  disabled?: boolean;
  /** An accessible label for the tab. Use this when the tab's text content does not adequately describe its purpose. */
  ariaLabel?: string;
}

// ── TableCell ─────────────────────────────────────────────────────────────

export interface SitTableCellProps extends SitBaseProps {
}

// ── TableHead ─────────────────────────────────────────────────────────────

export interface SitTableHeadProps extends SitBaseProps {
}

// ── TableRow ─────────────────────────────────────────────────────────────

export interface SitTableRowProps extends SitBaseProps {
}

// ── Table ─────────────────────────────────────────────────────────────

export interface SitTableProps extends SitBaseProps {
  /** Specifies the responsive breakpoint for the table.
Use "sm", "md", "lg", or "xl" to create responsive tables up to a particular breakpoint.
From that breakpoint and up, the table will behave normally and not scroll horizontally.
Use "always" to make the table always responsive.

(@deprecated) Deprecated since 3.9.0 legacy from v2 */
  responsive?: "sm" | "md" | "lg" | "xl" | "always";
  /** Array of strings to populate row header cells. */
  rowHeader?: string[];
  /** Array of strings to populate column header cells.
Only used when `headerPosition` is set to "vertical" or "both". */
  columnHeader?: string[];
  /** Two-dimensional array of strings or numbers to populate table data cells. */
  tableData?: Array<(string | number)[]>;
  /** Defines the placement of headers in the table.
Use "horizontal" for top headers only, "vertical" for left headers only,
or "both" for both row and column headers. */
  headerPosition?: "horizontal" | "vertical" | "both";
  /** Enables background styling on horizontal header rows.
When true, applies background color to header cells for better visual distinction. */
  headerBackground?: boolean;
  /** Enables borders around table cells.
When true, displays visible borders between all table cells. */
  tableBorder?: boolean;
  /** Controls the CSS `table-layout` algorithm.
Use "auto" to let the browser size columns based on content, or "fixed" to distribute column widths evenly regardless of content. */
  layout?: "auto" | "fixed";
}

// ── TableOfContents ─────────────────────────────────────────────────────────────

export interface SitTableOfContentsProps extends SitBaseProps {
}

// ── Textarea ─────────────────────────────────────────────────────────────

export interface SitTextareaProps extends SitBaseProps {
  /** The textarea's name attribute */
  name?: string;
  /** The textarea's value attribute. */
  value?: string;
  /** Sets the minimum length of the textarea */
  minlength?: number;
  /** Sets the maximum length of the textarea. When maxlength is defined, a word count appears on bottom right of the input */
  maxlength?: number;
  /** Enables spell checking on the textarea */
  spellcheck?: boolean;
  /** The number of rows to display by default. */
  rows?: number;
  /** The textarea's placeholder text. */
  placeholder?: string;
  /** Custom feedback text for error state when validated */
  invalidFeedback?: string;
  /** Autofocus the textarea */
  autofocus?: boolean;
  /** Makes the textarea readonly. */
  readonly?: boolean;
  /** Controls how the textarea can be resized. */
  resize?: "none" | "vertical" | "auto";
  /** The native textarea's inputmode attribute. It hints at the type of data that might be entered by the user while editing the element or its contents. This allows a browser to display an appropriate virtual keyboard. */
  inputmode?: | "none"
    | "text"
    | "decimal"
    | "numeric"
    | "tel"
    | "search"
    | "email"
    | "url";
  /** The native textarea's autocorrect attribute. */
  autocorrect?: boolean;
  /** Allows invalidFeedback, invalid and valid styles to be visible with the input */
  hasFeedback?: boolean;
  /** Makes the textarea as a required field. */
  required?: boolean;
  /** Disables native and sit validation for the textarea. */
  noValidate?: boolean;
  /** The textarea's hint text */
  hintText?: string;
  /** Returns the ValidityState object */
  validity?: ValidityState;
  /** Returns the validation message based on the ValidityState */
  validationMessage?: unknown;
  /** The input's label */
  label?: string;
  /** Disables the input. */
  disabled?: boolean;
  /** Marks the component as invalid. Replace the pseudo :invalid selector for absent in custom elements */
  invalid?: boolean;
  "onsit-change"?: SitEventHandler;
  onSitChange?: SitEventHandler;
  "onsit-input"?: SitEventHandler;
  onSitInput?: SitEventHandler;
  "onsit-focus"?: SitEventHandler;
  onSitFocus?: SitEventHandler;
  "onsit-blur"?: SitEventHandler;
  onSitBlur?: SitEventHandler;
  "onsit-invalid"?: SitEventHandler;
  onSitInvalid?: SitEventHandler;
  "onsit-valid"?: SitEventHandler;
  onSitValid?: SitEventHandler;
}

// ── ThumbnailCard ─────────────────────────────────────────────────────────────

export interface SitThumbnailCardProps extends SitBaseProps {
  /** Removes the card's internal padding when set to true. */
  noPadding?: boolean;
  /** Extends the link passed in either `footer` or `link`(deprecated) slot. */
  stretchedLink?: boolean;
  /** Disables the card */
  disabled?: boolean;
  /** When true, hides the default border of the card. */
  hideBorder?: boolean;
  /** When true, applies a tinted background color to the card. */
  tinted?: boolean;
  /** Sets the orientation of the card. Available options: `vertical`, `horizontal` */
  orientation?: CardOrientation;
}

// ── ToastContainer ─────────────────────────────────────────────────────────────

export interface SitToastContainerProps extends SitBaseProps {
  /** Controls the position of `sit-toast` within itself.
Since 3.7.1, the positions "top-start", "middle-start", "middle-center", and "middle-end" are deprecated. */
  position?: "top-start" | "top-center" | "top-end" | "middle-start" | "middle-center" | "middle-end" | "bottom-start" | "bottom-center" | "bottom-end";
}

// ── Toast ─────────────────────────────────────────────────────────────

export interface SitToastProps extends SitBaseProps {
  /** Controls the appearance of toast */
  show?: boolean;
  /** The header title of toast. It is required to assign a title to toast */
  title?: string;
  /** Controls whether the toast has fade animation during its appearance/disappearance */
  noAnimation?: boolean;
  /** Controls if the toast will hide itself after the delay time. Works with delay property */
  autohide?: boolean;
  /** The amount of time taken in miliseconds for toast to disappear after its first render. It takes effect only when autohide is set to true. Defaults to 5000ms */
  delay?: number;
  /** The variant styles of toast */
  variant?: "success" | "warning" | "danger" | "info";
  /** Controls whether or not the Toast is dismissible */
  dismissible?: boolean;
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-after-show"?: SitEventHandler;
  onSitAfterShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
  "onsit-after-hide"?: SitEventHandler;
  onSitAfterHide?: SitEventHandler;
}

// ── Tooltip ─────────────────────────────────────────────────────────────

export interface SitTooltipProps extends SitBaseProps {
  /** The tooltip's content. Must be text */
  content?: string;
  /** The placement of tooltip relative to its target */
  placement?: "top" | "bottom" | "left" | "right";
  /** The method to invoke the tooltip. `hover focus` is the default value which allows tooltip to be triggered via mouse hover and keyboard focus. Add `tabindex=0` for HTMLelements that are not tabbable. */
  trigger?: "click" | "hover" | "focus" | "hover focus";
  "onsit-show"?: SitEventHandler;
  onSitShow?: SitEventHandler;
  "onsit-after-show"?: SitEventHandler;
  onSitAfterShow?: SitEventHandler;
  "onsit-hide"?: SitEventHandler;
  onSitHide?: SitEventHandler;
  "onsit-after-hide"?: SitEventHandler;
  onSitAfterHide?: SitEventHandler;
}

// ---------------------------------------------------------------------------
// React JSX intrinsic element registrations
// ---------------------------------------------------------------------------

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "sit-accordion-item": React.DetailedHTMLProps<SitAccordionItemProps, HTMLElement>;
      "sit-accordion": React.DetailedHTMLProps<SitAccordionProps, HTMLElement>;
      "sit-alert-link": React.DetailedHTMLProps<SitAlertLinkProps, HTMLElement>;
      "sit-alert": React.DetailedHTMLProps<SitAlertProps, HTMLElement>;
      "sit-avatar": React.DetailedHTMLProps<SitAvatarProps, HTMLElement>;
      "sit-badge": React.DetailedHTMLProps<SitBadgeProps, HTMLElement>;
      "sit-breadcrumb-item": React.DetailedHTMLProps<SitBreadcrumbItemProps, HTMLElement>;
      "sit-breadcrumb": React.DetailedHTMLProps<SitBreadcrumbProps, HTMLElement>;
      "sit-button": React.DetailedHTMLProps<SitButtonProps, HTMLElement>;
      "sit-checkbox-group": React.DetailedHTMLProps<SitCheckboxGroupProps, HTMLElement>;
      "sit-checkbox": React.DetailedHTMLProps<SitCheckboxProps, HTMLElement>;
      "sit-card": React.DetailedHTMLProps<SitCardProps, HTMLElement>;
      "sit-close-button": React.DetailedHTMLProps<SitCloseButtonProps, HTMLElement>;
      "sit-combo-box-option": React.DetailedHTMLProps<SitComboBoxOptionProps, HTMLElement>;
      "sit-combo-box": React.DetailedHTMLProps<SitComboBoxProps, HTMLElement>;
      "sit-drawer": React.DetailedHTMLProps<SitDrawerProps, HTMLElement>;
      "sit-datepicker": React.DetailedHTMLProps<SitDatepickerProps, HTMLElement>;
      "sit-divider": React.DetailedHTMLProps<SitDividerProps, HTMLElement>;
      "sit-description-list-group": React.DetailedHTMLProps<SitDescriptionListGroupProps, HTMLElement>;
      "sit-description-list": React.DetailedHTMLProps<SitDescriptionListProps, HTMLElement>;
      "sit-dropdown-item": React.DetailedHTMLProps<SitDropdownItemProps, HTMLElement>;
      "sit-dropdown": React.DetailedHTMLProps<SitDropdownProps, HTMLElement>;
      "sit-file-upload": React.DetailedHTMLProps<SitFileUploadProps, HTMLElement>;
      "sit-footer-item": React.DetailedHTMLProps<SitFooterItemProps, HTMLElement>;
      "sit-footer": React.DetailedHTMLProps<SitFooterProps, HTMLElement>;
      "sit-icon-button": React.DetailedHTMLProps<SitIconButtonProps, HTMLElement>;
      "sit-icon-card": React.DetailedHTMLProps<SitIconCardProps, HTMLElement>;
      "sit-icon": React.DetailedHTMLProps<SitIconProps, HTMLElement>;
      "sit-image-card": React.DetailedHTMLProps<SitImageCardProps, HTMLElement>;
      "sit-input": React.DetailedHTMLProps<SitInputProps, HTMLElement>;
      "sit-icon-list": React.DetailedHTMLProps<SitIconListProps, HTMLElement>;
      "sit-link": React.DetailedHTMLProps<SitLinkProps, HTMLElement>;
      "sit-mainnav-dropdown": React.DetailedHTMLProps<SitMainnavDropdownProps, HTMLElement>;
      "sit-mainnav-item": React.DetailedHTMLProps<SitMainnavItemProps, HTMLElement>;
      "sit-mainnav": React.DetailedHTMLProps<SitMainnavProps, HTMLElement>;
      "sit-masthead": React.DetailedHTMLProps<SitMastheadProps, HTMLElement>;
      "sit-overflow-menu": React.DetailedHTMLProps<SitOverflowMenuProps, HTMLElement>;
      "sit-modal": React.DetailedHTMLProps<SitModalProps, HTMLElement>;
      "sit-pagination": React.DetailedHTMLProps<SitPaginationProps, HTMLElement>;
      "sit-popover": React.DetailedHTMLProps<SitPopoverProps, HTMLElement>;
      "sit-quantity-toggle": React.DetailedHTMLProps<SitQuantityToggleProps, HTMLElement>;
      "sit-progress-bar": React.DetailedHTMLProps<SitProgressBarProps, HTMLElement>;
      "sit-radio-group": React.DetailedHTMLProps<SitRadioGroupProps, HTMLElement>;
      "sit-radio": React.DetailedHTMLProps<SitRadioProps, HTMLElement>;
      "sit-select-option": React.DetailedHTMLProps<SitSelectOptionProps, HTMLElement>;
      "sit-select": React.DetailedHTMLProps<SitSelectProps, HTMLElement>;
      "sit-sidebar-group": React.DetailedHTMLProps<SitSidebarGroupProps, HTMLElement>;
      "sit-sidebar-item": React.DetailedHTMLProps<SitSidebarItemProps, HTMLElement>;
      "sit-sidebar-section": React.DetailedHTMLProps<SitSidebarSectionProps, HTMLElement>;
      "sit-sidebar": React.DetailedHTMLProps<SitSidebarProps, HTMLElement>;
      "sit-sidenav-item": React.DetailedHTMLProps<SitSidenavItemProps, HTMLElement>;
      "sit-sidenav-link": React.DetailedHTMLProps<SitSidenavLinkProps, HTMLElement>;
      "sit-sidenav": React.DetailedHTMLProps<SitSidenavProps, HTMLElement>;
      "sit-skeleton": React.DetailedHTMLProps<SitSkeletonProps, HTMLElement>;
      "sit-step": React.DetailedHTMLProps<SitStepProps, HTMLElement>;
      "sit-stepper": React.DetailedHTMLProps<SitStepperProps, HTMLElement>;
      "sit-spinner": React.DetailedHTMLProps<SitSpinnerProps, HTMLElement>;
      "sit-subnav-item": React.DetailedHTMLProps<SitSubnavItemProps, HTMLElement>;
      "sit-subnav": React.DetailedHTMLProps<SitSubnavProps, HTMLElement>;
      "sit-switch": React.DetailedHTMLProps<SitSwitchProps, HTMLElement>;
      "sit-system-banner-item": React.DetailedHTMLProps<SitSystemBannerItemProps, HTMLElement>;
      "sit-system-banner": React.DetailedHTMLProps<SitSystemBannerProps, HTMLElement>;
      "sit-tab-group": React.DetailedHTMLProps<SitTabGroupProps, HTMLElement>;
      "sit-tab-panel": React.DetailedHTMLProps<SitTabPanelProps, HTMLElement>;
      "sit-tab": React.DetailedHTMLProps<SitTabProps, HTMLElement>;
      "sit-table-cell": React.DetailedHTMLProps<SitTableCellProps, HTMLElement>;
      "sit-table-head": React.DetailedHTMLProps<SitTableHeadProps, HTMLElement>;
      "sit-table-row": React.DetailedHTMLProps<SitTableRowProps, HTMLElement>;
      "sit-table": React.DetailedHTMLProps<SitTableProps, HTMLElement>;
      "sit-table-of-contents": React.DetailedHTMLProps<SitTableOfContentsProps, HTMLElement>;
      "sit-textarea": React.DetailedHTMLProps<SitTextareaProps, HTMLElement>;
      "sit-thumbnail-card": React.DetailedHTMLProps<SitThumbnailCardProps, HTMLElement>;
      "sit-toast-container": React.DetailedHTMLProps<SitToastContainerProps, HTMLElement>;
      "sit-toast": React.DetailedHTMLProps<SitToastProps, HTMLElement>;
      "sit-tooltip": React.DetailedHTMLProps<SitTooltipProps, HTMLElement>;
    }
  }
}

// ---------------------------------------------------------------------------
// Global HTMLElementTagNameMap augmentation (vanilla TypeScript / non-React)
// ---------------------------------------------------------------------------

declare global {
  interface HTMLElementTagNameMap {
    "sit-accordion-item": HTMLElement;
    "sit-accordion": HTMLElement;
    "sit-alert-link": HTMLElement;
    "sit-alert": HTMLElement;
    "sit-avatar": HTMLElement;
    "sit-badge": HTMLElement;
    "sit-breadcrumb-item": HTMLElement;
    "sit-breadcrumb": HTMLElement;
    "sit-button": HTMLElement;
    "sit-checkbox-group": HTMLElement;
    "sit-checkbox": HTMLElement;
    "sit-card": HTMLElement;
    "sit-close-button": HTMLElement;
    "sit-combo-box-option": HTMLElement;
    "sit-combo-box": HTMLElement;
    "sit-drawer": HTMLElement;
    "sit-datepicker": HTMLElement;
    "sit-divider": HTMLElement;
    "sit-description-list-group": HTMLElement;
    "sit-description-list": HTMLElement;
    "sit-dropdown-item": HTMLElement;
    "sit-dropdown": HTMLElement;
    "sit-file-upload": HTMLElement;
    "sit-footer-item": HTMLElement;
    "sit-footer": HTMLElement;
    "sit-icon-button": HTMLElement;
    "sit-icon-card": HTMLElement;
    "sit-icon": HTMLElement;
    "sit-image-card": HTMLElement;
    "sit-input": HTMLElement;
    "sit-icon-list": HTMLElement;
    "sit-link": HTMLElement;
    "sit-mainnav-dropdown": HTMLElement;
    "sit-mainnav-item": HTMLElement;
    "sit-mainnav": HTMLElement;
    "sit-masthead": HTMLElement;
    "sit-overflow-menu": HTMLElement;
    "sit-modal": HTMLElement;
    "sit-pagination": HTMLElement;
    "sit-popover": HTMLElement;
    "sit-quantity-toggle": HTMLElement;
    "sit-progress-bar": HTMLElement;
    "sit-radio-group": HTMLElement;
    "sit-radio": HTMLElement;
    "sit-select-option": HTMLElement;
    "sit-select": HTMLElement;
    "sit-sidebar-group": HTMLElement;
    "sit-sidebar-item": HTMLElement;
    "sit-sidebar-section": HTMLElement;
    "sit-sidebar": HTMLElement;
    "sit-sidenav-item": HTMLElement;
    "sit-sidenav-link": HTMLElement;
    "sit-sidenav": HTMLElement;
    "sit-skeleton": HTMLElement;
    "sit-step": HTMLElement;
    "sit-stepper": HTMLElement;
    "sit-spinner": HTMLElement;
    "sit-subnav-item": HTMLElement;
    "sit-subnav": HTMLElement;
    "sit-switch": HTMLElement;
    "sit-system-banner-item": HTMLElement;
    "sit-system-banner": HTMLElement;
    "sit-tab-group": HTMLElement;
    "sit-tab-panel": HTMLElement;
    "sit-tab": HTMLElement;
    "sit-table-cell": HTMLElement;
    "sit-table-head": HTMLElement;
    "sit-table-row": HTMLElement;
    "sit-table": HTMLElement;
    "sit-table-of-contents": HTMLElement;
    "sit-textarea": HTMLElement;
    "sit-thumbnail-card": HTMLElement;
    "sit-toast-container": HTMLElement;
    "sit-toast": HTMLElement;
    "sit-tooltip": HTMLElement;
  }
}
