const LG_BREAKPOINT = 1024;
const MD_BREAKPOINT = 768;
const SM_BREAKPOINT = 512;
const XL_BREAKPOINT = 1280;
const XXL_BREAKPOINT = 1440;

export { LG_BREAKPOINT, MD_BREAKPOINT, SM_BREAKPOINT, XL_BREAKPOINT, XXL_BREAKPOINT };
//# sourceMappingURL=breakpoints.js.map
