import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import "@sit-canvas/canvas-web-component/lib/themes/day.css";
import CanvasLibraryLoader from "./canvas";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = (await headers()).get("x-nonce") ?? undefined;

  return (
    <html lang="en">
      <head>
        <CanvasLibraryLoader nonce={nonce} />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
