'use client';
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var lit = require('lit');

var css_248z = lit.css`:host([variant=border][last-of-type]) .accordion-item{border-bottom:none}:host([density=compact]) .accordion-btn{font-size:var(--sit-font-size-subtitle-sm);line-height:var(--sit-line-height-2-xs);padding:var(--sit-padding-md)}:host([density=compact]) .accordion-body{font-size:var(--sit-font-size-label-sm);line-height:var(--sit-line-height-2-xs)}:host([density=compact]) .content{padding:var(--sit-padding-xs) var(--sit-padding-md) var(--sit-padding-md)}:host([density=spacious]) .accordion-btn{font-size:var(--sit-font-size-heading-sm);letter-spacing:var(--sit-letter-spacing-tight);line-height:var(--sit-line-height-sm);padding:var(--sit-padding-xl)}:host([density=spacious]) .content{padding:var(--sit-padding-xs) var(--sit-padding-xl) var(--sit-padding-xl)}.accordion-item{border-bottom:var(--sit-border-width-1) solid var(--sit-border-color-muted)}.accordion-btn{align-items:center;background-color:var(--sit-bg-transparent);border:0;color:var(--sit-color-default);display:flex;font-size:var(--sit-font-size-subtitle-md);font-weight:var(--sit-font-weight-semibold);gap:var(--sit-gap-md);line-height:var(--sit-line-height-xs);overflow-anchor:none;padding:var(--sit-padding-lg);text-align:left;width:100%}@media (prefers-reduced-motion:reduce){.accordion-btn,.accordion-btn:after{transition:none}}.accordion-btn:not(.disabled):hover,.accordion-btn:not(:disabled):hover{background-color:var(--sit-bg-translucent-subtle);z-index:2}.accordion-btn:not(.disabled):focus-visible,.accordion-btn:not(:disabled):focus-visible{background-color:var(--sit-bg-translucent-subtle);outline:var(--sit-outline-focus);outline-offset:var(--sit-outline-offset-focus);z-index:3}.accordion-btn.disabled,.accordion-btn:disabled{cursor:not-allowed;opacity:var(--sit-opacity-40)}slot[name=badge]::slotted(*){margin-left:auto}.accordion-header__trailing{display:flex;gap:var(--sit-gap-md);margin-left:auto}slot[name=caret] sit-icon,slot[name=caret]::slotted(*){color:var(--sit-color-subtle);transition:transform .2s ease-in-out}.accordion-btn:not(.collapsed) slot[name=caret] sit-icon,.accordion-btn:not(.collapsed) slot[name=caret]::slotted(*){transform:rotate(-180deg)}.accordion-body{color:var(--sit-body-color-subtle);font-size:var(--sit-font-size-label-md);line-height:var(--sit-line-height-xs);overflow:hidden;padding:0}.content{display:block;padding:var(--sit-padding-xs) var(--sit-padding-lg) var(--sit-padding-lg)}.hidden{display:none}`;

exports["default"] = css_248z;
//# sourceMappingURL=accordion-item.cjs.js.map
