'use client';
import { css } from 'lit';

var css_248z = css`:host{--sit-spinner-bg:var(--sit-primary-surface-default);display:inline-flex}:host([variant=neutral]){--sit-spinner-bg:var(--sit-neutral-surface-default)}:host([tone=neutral]){--sit-spinner-bg:var(--sit-surface-inverse)}:host([tone=inverse]){--sit-spinner-bg:var(--sit-surface-default)}:host([tone=fixed-light]){--sit-spinner-bg:var(--sit-surface-fixed-light)}:host([tone=fixed-dark]){--sit-spinner-bg:var(--sit-surface-fixed-dark)}.spinner-wrapper{align-items:center;display:flex;flex-direction:column;gap:var(--sit-gap-2-xs)}.spinner-wrapper.spinner-wrapper--horizontal{flex-direction:row}.spinner-wrapper__spinner{--border-thickness:4px;animation:spinner .75s linear infinite;border:var(--border-thickness) solid var(--sit-bg-translucent);border-radius:50%;border-right:var(--border-thickness) solid var(--sit-spinner-bg);color:var(--sit-spinner-color);display:inline-flex;height:var(--sit-dimension-32);width:var(--sit-dimension-32)}.spinner-wrapper__spinner--xs{--border-thickness:2px;height:var(--sit-dimension-16);width:var(--sit-dimension-16)}.spinner-wrapper__spinner--sm{--border-thickness:3px;height:var(--sit-dimension-24);width:var(--sit-dimension-24)}.spinner-wrapper__spinner--lg{--border-thickness:6px;height:var(--sit-dimension-48);width:var(--sit-dimension-48)}.spinner-wrapper__spinner--xl{--border-thickness:8px;height:var(--sit-dimension-64);width:var(--sit-dimension-64)}.spinner-wrapper__label{color:var(--sit-neutral-color-default);font-size:var(--sit-font-size-label-sm)}@media (prefers-reduced-motion:reduce){.spinner-wrapper__spinner{animation-duration:1.5s}}

/*! CSS Used keyframes */@keyframes spinner{to{transform:rotate(1turn)}}.sr-only{clip:rect(0,0,0,0);border:0;height:1px;overflow:hidden;padding:0;position:absolute;white-space:nowrap;width:1px}`;

export { css_248z as default };
//# sourceMappingURL=spinner.js.map
