'use client';
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var lit = require('lit');

var css_248z = lit.css`:host([size=md]) .drawer-end .drawer-panel,:host([size=md]) .drawer-start .drawer-panel{max-width:var(--sit-dimension-768)}:host([size=md]) .drawer-bottom .drawer-panel,:host([size=md]) .drawer-top .drawer-panel{max-height:var(--sit-dimension-768)}:host([size=lg]) .drawer-end .drawer-panel,:host([size=lg]) .drawer-start .drawer-panel{max-width:var(--sit-dimension-1024)}:host([size=lg]) .drawer-bottom .drawer-panel,:host([size=lg]) .drawer-top .drawer-panel{max-height:var(--sit-dimension-1024)}.drawer{height:100%;inset-inline-start:0;overflow:hidden;pointer-events:none;top:0;width:100%}.drawer-fixed{position:fixed;z-index:var(--sit-z-index-modal)}.drawer-panel{background-color:var(--sit-surface-default);display:flex;flex-direction:column;overflow:auto;pointer-events:all;position:absolute;z-index:2}.drawer-panel:focus{outline:none}.drawer-top .drawer-panel{bottom:auto;height:80%;inset-inline-end:auto;inset-inline-start:0;max-height:var(--sit-dimension-512);top:0;width:100%}.drawer-end .drawer-panel{bottom:auto;height:100%;inset-inline-end:0;inset-inline-start:auto;max-width:var(--sit-dimension-512);top:0;width:80%}.drawer-bottom .drawer-panel{bottom:0;height:80%;inset-inline-end:auto;inset-inline-start:0;max-height:var(--sit-dimension-512);top:auto;width:100%}.drawer-start .drawer-panel{bottom:auto;height:100%;inset-inline-end:auto;inset-inline-start:0;max-width:var(--sit-dimension-512);top:0;width:80%}.drawer-close-wrapper{position:sticky;top:0}sit-close-button.drawer-close{inset-inline-end:8px;position:absolute;top:8px}.drawer-header{display:flex;flex-direction:column;gap:var(--sit-gap-xs);padding:var(--sit-padding-lg) var(--sit-padding-lg) var(--sit-padding-none)}slot[name=title]::slotted(*){color:var(--sit-color-default)!important;font-size:var(--sit-font-size-heading-sm)!important;margin-bottom:var(--sit-margin-none)!important}slot[name=description]::slotted(*){color:var(--sit-color-subtle);margin-bottom:var(--sit-margin-none)!important}slot[name=footer]::slotted(*){background-color:var(--sit-surface-default);bottom:0;padding:var(--sit-padding-lg);position:sticky}.drawer-body{-webkit-overflow-scrolling:touch;display:block;flex:1 1 auto;overflow:hidden;padding:var(--sit-padding-lg)}.drawer-overlay{background-color:var(--sit-bg-overlay);display:block;inset:0;pointer-events:all;position:fixed}.drawer-contained .drawer-overlay{display:none}.drawer-contained{height:unset;width:unset}@media screen and (min-width:512px){.drawer-body{padding:var(--sit-padding-2-xl)}.drawer-header{padding:var(--sit-padding-2-xl) var(--sit-padding-2-xl) var(--sit-padding-none)}slot[name=footer]::slotted(*){padding:var(--sit-padding-2-xl)}}`;

exports["default"] = css_248z;
//# sourceMappingURL=drawer.cjs.js.map
